/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rose;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Joel
 */
public class JIFraGiveBulkBH extends javax.swing.JInternalFrame {

    DefaultTableModel model1;
    DefaultTableModel model2;
    Connection con = null;
    ResultSet rs = null;
    ResultSet rs1 = null;
    ResultSet rs2 = null;
    Statement stmt = null;
    Statement stmt1 = null;
    Statement stmt2 = null;
    String query = null;
    String[] tailrno, bhno;
    int rowcount = 0, temp = 0, item_no = 0, stsl;
    int[] selected;
    String today = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
     

    public JIFraGiveBulkBH() {
        try {
            initComponents();
            model1 = (DefaultTableModel) jtblStitchingMaster.getModel();
            model2 = (DefaultTableModel) jtblButtonholeMaster.getModel();
            jtblStitchingMaster.setAutoCreateRowSorter(true);
            con = new DBConnection().connect();
            stmt = con.createStatement();
            query = "select tailor_no,tailor_name from mst_tailor where flag!='D' and year(date_created)='" + Global.year + "'";
            rs = stmt.executeQuery(query);
            jcmbStitchingMaster.addItem("");
            while (rs.next()) {
                jcmbStitchingMaster.addItem(rs.getString(1) + "   " + rs.getString(2));
            }
            query = "select bh_no,bh_master_name from mst_buttonhole where flag!='D' and year(date_created)='" + Global.year + "'";
            rs = stmt.executeQuery(query);
            jcmbButtonholeMaster.addItem("");
            while (rs.next()) {
                jcmbButtonholeMaster.addItem(rs.getString(1) + "   " + rs.getString(2));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } finally {
            try {
                if (!rs.isClosed()) {
                    rs.close();
                }
                if (!con.isClosed()) {
                    con.close();
                }
                if (!stmt.isClosed()) {
                    stmt.isClosed();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jcmbStitchingMaster = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jdteDate = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblStitchingMaster = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jcmbButtonholeMaster = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jdteDate1 = new com.toedter.calendar.JDateChooser();
        jbtnView = new javax.swing.JButton();
        jbtnGive = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblButtonholeMaster = new javax.swing.JTable();

        setClosable(true);
        setTitle("Give Buttonhole Bulk");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setText("Stitching Master");

        jcmbStitchingMaster.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbStitchingMasterItemStateChanged(evt);
            }
        });

        jLabel3.setText("Date");

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtblStitchingMaster.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Order No.", "Student Name", "Stitching Master", "Item", "Quantity", "Date Given", "Date Recieved", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblStitchingMaster);
        jtblStitchingMaster.getColumnModel().getColumn(0).setMinWidth(0);
        jtblStitchingMaster.getColumnModel().getColumn(0).setPreferredWidth(0);
        jtblStitchingMaster.getColumnModel().getColumn(0).setMaxWidth(0);
        jtblStitchingMaster.getColumnModel().getColumn(1).setPreferredWidth(70);
        jtblStitchingMaster.getColumnModel().getColumn(5).setPreferredWidth(55);
        jtblStitchingMaster.getColumnModel().getColumn(6).setPreferredWidth(100);
        jtblStitchingMaster.getColumnModel().getColumn(7).setPreferredWidth(100);
        jtblStitchingMaster.getColumnModel().getColumn(8).setPreferredWidth(50);

        jLabel5.setText("Buttonhole Master");

        jcmbButtonholeMaster.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbButtonholeMasterItemStateChanged(evt);
            }
        });

        jLabel6.setText("Date");

        jdteDate1.setDateFormatString("dd-MM-yyyy");

        jbtnView.setText("View");
        jbtnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnViewActionPerformed(evt);
            }
        });

        jbtnGive.setText("Give");
        jbtnGive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGiveActionPerformed(evt);
            }
        });

        jtblButtonholeMaster.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Order No.", "Student Name", "Buttonhole Master", "Item", "Quantity", "Date Given", "Date Received", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtblButtonholeMaster);
        jtblButtonholeMaster.getColumnModel().getColumn(0).setMinWidth(0);
        jtblButtonholeMaster.getColumnModel().getColumn(0).setPreferredWidth(0);
        jtblButtonholeMaster.getColumnModel().getColumn(0).setMaxWidth(0);
        jtblButtonholeMaster.getColumnModel().getColumn(1).setPreferredWidth(70);
        jtblButtonholeMaster.getColumnModel().getColumn(5).setPreferredWidth(55);
        jtblButtonholeMaster.getColumnModel().getColumn(6).setPreferredWidth(100);
        jtblButtonholeMaster.getColumnModel().getColumn(7).setPreferredWidth(100);
        jtblButtonholeMaster.getColumnModel().getColumn(8).setPreferredWidth(50);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcmbStitchingMaster, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdteDate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcmbButtonholeMaster, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdteDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnView)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnGive)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jcmbStitchingMaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdteDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jcmbButtonholeMaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jdteDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnView)
                        .addComponent(jbtnGive)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcmbStitchingMasterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbStitchingMasterItemStateChanged
    }//GEN-LAST:event_jcmbStitchingMasterItemStateChanged
    private void populatetailortable() {
        try {
            rowcount = model1.getRowCount();
            for (int i = 0; i < rowcount; i++) {
                model1.removeRow(0);
            }
            tailrno = jcmbStitchingMaster.getSelectedItem().toString().split("   ");
            con = new DBConnection().connect();
            stmt = con.createStatement();
            if (jdteDate.getDate() == null) {
                query = "select a.sl_no,b.order_no,b.student_name,e.tailor_name,d.item_name,a.qty,a.date_given,a.date_recieved,a.status from trn_stitching a left join mst_student b on a.stsl_no = b.stsl_no left join mst_item d on a.item_no = d.item_no left join mst_tailor e on a.tailor_no = e.tailor_no where a.tailor_no = '" + tailrno[0] + "' and b.school_no = '" + Global.getSchoolno() + "' and d.buttonhole = '1'  and a.status='C' and a.flag!='D'  and b.flag!='D'  and d.flag!='D'  and e.flag!='D'";
            } else {
                query = "select a.sl_no,b.order_no,b.student_name,e.tailor_name,d.item_name,a.qty,a.date_given,a.date_recieved,a.status from trn_stitching a left join mst_student b on a.stsl_no = b.stsl_no left join mst_item d on a.item_no = d.item_no left join mst_tailor e on a.tailor_no = e.tailor_no where a.tailor_no = '" + tailrno[0] + "' and b.school_no = '" + Global.getSchoolno() + "' and d.buttonhole = '1' and a.date_recieved = '" + new SimpleDateFormat("yyyy-MM-dd").format(jdteDate.getDate()) + "' and a.status='C' and a.flag!='D'  and b.flag!='D'  and d.flag!='D'  and e.flag!='D'";
            }
            rs = stmt.executeQuery(query);
            while (rs.next()) {
                temp = model1.getRowCount();
                model1.addRow(new Object[]{});
                jtblStitchingMaster.setValueAt(rs.getString(1), temp, 0);
                jtblStitchingMaster.setValueAt(rs.getString(2), temp, 1);
                jtblStitchingMaster.setValueAt(rs.getString(3), temp, 2);
                jtblStitchingMaster.setValueAt(rs.getString(4), temp, 3);
                jtblStitchingMaster.setValueAt(rs.getString(5), temp, 4);
                jtblStitchingMaster.setValueAt(rs.getString(6), temp, 5);
                jtblStitchingMaster.setValueAt(rs.getString(7), temp, 6);
                jtblStitchingMaster.setValueAt(rs.getString(8), temp, 7);
                jtblStitchingMaster.setValueAt(rs.getString(9), temp, 8);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } finally {
            try {
                if (!rs.isClosed()) {
                    rs.close();
                }
                if (!con.isClosed()) {
                    con.close();
                }
                if (!stmt.isClosed()) {
                    stmt.isClosed();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }

    private void populateBHtable() {
        try {
            rowcount = model2.getRowCount();
            for (int i = 0; i < rowcount; i++) {
                model2.removeRow(0);
            }

            bhno = jcmbButtonholeMaster.getSelectedItem().toString().split("   ");
            con = new DBConnection().connect();
            stmt = con.createStatement();
            if (jdteDate1.getDate() == null) {
                query = "select a.sl_no,b.order_no,b.student_name,e.bh_master_name,d.item_name,a.qty,a.date_given,a.date_recieved,a.status from trn_buttonhole a left join mst_student b on a.stsl_no = b.stsl_no left join mst_item d on a.item_no = d.item_no left join mst_buttonhole e on a.bh_no = e.bh_no where a.bh_no = '" + bhno[0] + "' and b.school_no = '" + Global.getSchoolno() + "' and a.status = 'P' and a.flag!='D' and b.flag!='D' and d.flag!='D' and e.flag!='D'";
            } else {
                query = "select a.sl_no,b.order_no,b.student_name,e.bh_master_name,d.item_name,a.qty,a.date_given,a.date_recieved,a.status from trn_buttonhole a left join mst_student b on a.stsl_no = b.stsl_no left join mst_item d on a.item_no = d.item_no left join mst_buttonhole e on a.bh_no = e.bh_no where a.bh_no = '" + bhno[0] + "' and b.school_no = '" + Global.getSchoolno() + "' and a.date_given = '" + new SimpleDateFormat("yyyy-MM-dd").format(jdteDate1.getDate()) + "' and a.status = 'P' and a.flag!='D' and b.flag!='D' and d.flag!='D' and e.flag!='D'";
            }
            rs = stmt.executeQuery(query);
            while (rs.next()) {
                model2.addRow(new Object[]{});
                temp = model2.getRowCount() - 1;
                jtblButtonholeMaster.setValueAt(rs.getString(1), temp, 0);
                jtblButtonholeMaster.setValueAt(rs.getString(2), temp, 1);
                jtblButtonholeMaster.setValueAt(rs.getString(3), temp, 2);
                jtblButtonholeMaster.setValueAt(rs.getString(4), temp, 3);
                jtblButtonholeMaster.setValueAt(rs.getString(5), temp, 4);
                jtblButtonholeMaster.setValueAt(rs.getString(6), temp, 5);
                jtblButtonholeMaster.setValueAt(rs.getString(7), temp, 6);
                jtblButtonholeMaster.setValueAt(rs.getString(8), temp, 7);
                jtblButtonholeMaster.setValueAt(rs.getString(9), temp, 8);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } finally {
            try {
                if (!rs.isClosed()) {
                    rs.close();
                }
                if (!con.isClosed()) {
                    con.close();
                }
                if (!stmt.isClosed()) {
                    stmt.isClosed();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jcmbStitchingMaster.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(this, "Please select a stitching master", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            populatetailortable();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcmbButtonholeMasterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbButtonholeMasterItemStateChanged
    }//GEN-LAST:event_jcmbButtonholeMasterItemStateChanged

    private void jbtnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnViewActionPerformed
        if (jcmbButtonholeMaster.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(this, "Please select a buttonhole master", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            populateBHtable();
        }
    }//GEN-LAST:event_jbtnViewActionPerformed

    private void jbtnGiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGiveActionPerformed
        if (jcmbButtonholeMaster.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(this, "Please select a buttonhole master", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else if (jdteDate1.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please select a date", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtblStitchingMaster.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Please select a record from stitching master table to insert", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                con = new DBConnection().connect();
                stmt1 = con.createStatement();
                stmt = con.createStatement();
                stmt2 = con.createStatement();
                bhno = jcmbButtonholeMaster.getSelectedItem().toString().split("   ");
                con.setAutoCommit(false);
                int i = 0;
                selected = jtblStitchingMaster.getSelectedRows();
                for (int j = 0; j < selected.length; j++) {
                    temp = 0;
                    query = "select item_no from trn_stitching where sl_no = '" + jtblStitchingMaster.getValueAt(selected[j], 0) + "' and flag!='D' and year(date_created)='"+Global.year+"'";
                    rs = stmt.executeQuery(query);
                    if (rs.next()) {
                        item_no = rs.getInt(1);
                    }
                    query = "select stsl_no from mst_student where  order_no = '" + jtblStitchingMaster.getValueAt(selected[j], 1) + "' and flag!='D' and year(date_created)='"+Global.year+"'";
                    rs = stmt.executeQuery(query);
                    if (rs.next()) {
                        stsl = rs.getInt(1);
                    }
                    query = "select a.item_no,sum(a.qty) from trn_stitching a join mst_item b on a.item_no = b.item_no where a.stsl_no = '" + stsl + "' and b.buttonhole = '1' and a.item_no = '" + item_no + "' and a.status = 'C' and a.flag!='D' and b.flag!='D' and year(a.date_created)='"+Global.year+"' and year(b.date_created)='"+Global.year+"' group by a.item_no";
                    rs = stmt.executeQuery(query);
                    if (rs.next()) {
                        if (rs.getInt(2) >= Integer.parseInt(jtblStitchingMaster.getValueAt(selected[j], 5).toString())) {
                            query = "select item_no,sum(qty) from trn_buttonhole where stsl_no = '" + stsl + "' and item_no ='" + item_no + "' and flag!='D' and year(a.date_created)='"+Global.year+"' and year(b.date_created)='"+Global.year+"' group by item_no";
                            rs1 = stmt1.executeQuery(query);
                            if (rs1.next()) {
                                temp = rs.getInt(2) - rs1.getInt(2);
                                if (temp > 0) {
                                    if (temp >= Integer.parseInt(jtblStitchingMaster.getValueAt(selected[j], 5).toString())) {
                                        query = "select sl_no,qty from trn_buttonhole where stsl_no ='" + stsl + "' and item_no = '" + rs.getString(1) + "' and date_given = '" + today + "' and bh_no = '" + bhno[0] + "' and status='P' and flag!='D' and year(a.date_created)='"+Global.year+"'";
                                        rs2 = stmt2.executeQuery(query);
                                        if (rs2.next()) {
                                            temp = Integer.parseInt(jtblStitchingMaster.getValueAt(selected[j], 5).toString()) + rs2.getInt(2);
                                            query = "update trn_buttonhole set qty = '" + temp + "' where sl_no='" + rs2.getString(1) + "'";
                                            i = i + stmt2.executeUpdate(query);
                                        } else {
                                            query = "insert into trn_buttonhole(bh_no,stsl_no,item_no,qty,status,date_given,flag,date_created) values('" + bhno[0] + "','" + stsl + "','" + item_no + "','" + jtblStitchingMaster.getValueAt(selected[j], 5).toString() + "','P','" + new SimpleDateFormat("yyyy-MM-dd").format(jdteDate1.getDate()) + "','I','" + today + "')";
                                            i = i + stmt2.executeUpdate(query);
                                        }
                                    }
//                                    } else {
//                                        JOptionPane.showMessageDialog(this, "The quantity entered has exceeded please check!", "Info", JOptionPane.INFORMATION_MESSAGE);
//                                    }
                                }
                            } else {
                                query = "insert into trn_buttonhole(bh_no,stsl_no,item_no,qty,status,date_given,flag,date_created) values('" + bhno[0] + "','" + stsl + "','" + item_no + "','" + jtblStitchingMaster.getValueAt(selected[j], 5).toString() + "','P','" + new SimpleDateFormat("yyyy-MM-dd").format(jdteDate1.getDate()) + "','I','" + today + "')";
                                i = i + stmt1.executeUpdate(query);
                            }
                        }
//                        } else {
//                            JOptionPane.showMessageDialog(this, "Quantity entered is not available at the moment!", "Info", JOptionPane.INFORMATION_MESSAGE);
//                        }
                    }
                }
                if (i > 0) {
                    con.commit();
                    JOptionPane.showMessageDialog(this, "Inserted Successfull!", "Info", JOptionPane.INFORMATION_MESSAGE);
                    populateBHtable();
                    jdteDate1.setDate(null);
                }
            } catch (SQLException ex) {
                Logger.getLogger(JIFraGiveBulkBH.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    if (!rs.isClosed()) {
                        rs.close();
                    }
                    if (!rs1.isClosed()) {
                        rs1.close();
                    }
                    if (!rs2.isClosed()) {
                        rs2.close();
                    }
                    if (!con.isClosed()) {
                        con.close();
                    }
                    if (!stmt.isClosed()) {
                        stmt.isClosed();
                    }
                    if (!stmt1.isClosed()) {
                        stmt1.isClosed();
                    }
                    if (!stmt2.isClosed()) {
                        stmt2.isClosed();
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jbtnGiveActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnGive;
    private javax.swing.JButton jbtnView;
    private javax.swing.JComboBox jcmbButtonholeMaster;
    private javax.swing.JComboBox jcmbStitchingMaster;
    private com.toedter.calendar.JDateChooser jdteDate;
    private com.toedter.calendar.JDateChooser jdteDate1;
    private javax.swing.JTable jtblButtonholeMaster;
    private javax.swing.JTable jtblStitchingMaster;
    // End of variables declaration//GEN-END:variables
}
