/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rose;

import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Joel
 */
public class JIFraGiveBulkIroning extends javax.swing.JInternalFrame {

    DefaultTableModel model1;
    DefaultTableModel model2;
    Connection con = null;
    ResultSet rs = null;
    ResultSet rs1 = null;
    ResultSet rs2 = null;
    Statement stmt = null;
    Statement stmt1 = null;
    Statement stmt2 = null;
    String query = null;
    String[] Labourerno, ironno;
    int rowcount = 0, temp = 0, item_no = 0, stsl;
    int[] selected;
    String today = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
     

    public JIFraGiveBulkIroning() {
        try {
            initComponents();
            jcmbType.addItem("");
            jcmbType.addItem("Stitching");
            jcmbType.addItem("Buttonhole");
            model1 = (DefaultTableModel) jtblLabourer.getModel();
            model2 = (DefaultTableModel) jtblIroningMaster.getModel();
            con = new DBConnection().connect();
            stmt = con.createStatement();
            query = "select iron_no,iron_name from mst_ironing where flag!='D' and year(date_created)='" + Global.year + "'";
            rs = stmt.executeQuery(query);
            jcmbIroningMaster.addItem("");
            while (rs.next()) {
                jcmbIroningMaster.addItem(rs.getString(1) + "   " + rs.getString(2));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } finally {
            try {
                if (!rs.isClosed()) {
                    rs.close();
                }
                if (!con.isClosed()) {
                    con.close();
                }
                if (!stmt.isClosed()) {
                    stmt.isClosed();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcmbType = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jcmbLabourer = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jdteDate = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblLabourer = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jcmbIroningMaster = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jdteDate1 = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblIroningMaster = new javax.swing.JTable();
        jbtnView = new javax.swing.JButton();
        jbtnGive = new javax.swing.JButton();

        setClosable(true);
        setTitle("Give Bulk Ironing");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Type");

        jcmbType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbTypeItemStateChanged(evt);
            }
        });

        jLabel2.setText("Labourer");

        jLabel3.setText("Date");

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtblLabourer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Order No.", "Student Name", "Stitching Master", "Item", "Quantity", "Date Given", "Date Recieved", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblLabourer);
        jtblLabourer.getColumnModel().getColumn(0).setMinWidth(0);
        jtblLabourer.getColumnModel().getColumn(0).setPreferredWidth(0);
        jtblLabourer.getColumnModel().getColumn(0).setMaxWidth(0);
        jtblLabourer.getColumnModel().getColumn(1).setPreferredWidth(70);
        jtblLabourer.getColumnModel().getColumn(5).setPreferredWidth(55);
        jtblLabourer.getColumnModel().getColumn(6).setPreferredWidth(100);
        jtblLabourer.getColumnModel().getColumn(7).setPreferredWidth(100);
        jtblLabourer.getColumnModel().getColumn(8).setPreferredWidth(50);

        jLabel4.setText("Ironing Master");

        jLabel5.setText("Date");

        jdteDate1.setDateFormatString("dd-MM-yyyy");

        jtblIroningMaster.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Order No.", "Student Name", "Ironing Master", "Item", "Quantity", "Date Given", "Date Received", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtblIroningMaster);
        jtblIroningMaster.getColumnModel().getColumn(0).setMinWidth(0);
        jtblIroningMaster.getColumnModel().getColumn(0).setPreferredWidth(0);
        jtblIroningMaster.getColumnModel().getColumn(0).setMaxWidth(0);
        jtblIroningMaster.getColumnModel().getColumn(1).setPreferredWidth(70);
        jtblIroningMaster.getColumnModel().getColumn(5).setPreferredWidth(55);
        jtblIroningMaster.getColumnModel().getColumn(6).setPreferredWidth(100);
        jtblIroningMaster.getColumnModel().getColumn(7).setPreferredWidth(100);
        jtblIroningMaster.getColumnModel().getColumn(8).setPreferredWidth(50);

        jbtnView.setText("View");
        jbtnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnViewActionPerformed(evt);
            }
        });

        jbtnGive.setText("Give");
        jbtnGive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcmbLabourer, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdteDate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcmbIroningMaster, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdteDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnView)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnGive)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jdteDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jcmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jcmbLabourer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jcmbIroningMaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jdteDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnView)
                        .addComponent(jbtnGive)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcmbTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbTypeItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (jcmbType.getSelectedItem().equals("")) {
                jcmbLabourer.removeAllItems();
            } else {
                try {
                    con = new DBConnection().connect();
                    stmt = con.createStatement();
                    if (jcmbType.getSelectedItem().equals("Stitching")) {
                        query = "select tailor_no,tailor_name from mst_tailor where flag!='D' and year(date_created)='" + Global.year + "'";
                    } else if (jcmbType.getSelectedItem().equals("Buttonhole")) {
                        query = "select bh_no,bh_master_name from mst_buttonhole where flag!='D' and year(date_created)='" + Global.year + "'";
                    }
                    rs = stmt.executeQuery(query);
                    jcmbLabourer.removeAllItems();
                    jcmbLabourer.addItem("");
                    while (rs.next()) {
                        jcmbLabourer.addItem(rs.getString(1) + "   " + rs.getString(2));
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                } finally {
                    try {
                        if (!rs.isClosed()) {
                            rs.close();
                        }
                        if (!con.isClosed()) {
                            con.close();
                        }
                        if (!stmt.isClosed()) {
                            stmt.isClosed();
                        }
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage());
                    }
                }
            }
        }
    }//GEN-LAST:event_jcmbTypeItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jcmbLabourer.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(this, "Please select a labourer", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            populatetailortable();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnViewActionPerformed
        if (jcmbIroningMaster.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(this, "Please select a ironing master", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            populateIroningtable();
        }
    }//GEN-LAST:event_jbtnViewActionPerformed

    private void jbtnGiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGiveActionPerformed
        if (jcmbIroningMaster.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(this, "Please select a ironing master", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else if (jdteDate1.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please select a date", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtblLabourer.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Please select a record from ironing master table to insert", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                con = new DBConnection().connect();
                stmt1 = con.createStatement();
                stmt = con.createStatement();
                stmt2 = con.createStatement();
                ironno = jcmbIroningMaster.getSelectedItem().toString().split("   ");
                con.setAutoCommit(false);
                int i = 0;
                temp = 0;
                selected = jtblLabourer.getSelectedRows();
                for (int j = 0; j < selected.length; j++) {
                    temp = 0;
                    if (jcmbType.getSelectedItem().equals("Stitching")) {
                        query = "select item_no from trn_stitching where sl_no = '" + jtblLabourer.getValueAt(selected[j], 0) + "' and flag!='D' and year(date_created)='"+Global.year+"'";
                    } else if (jcmbType.getSelectedItem().equals("Buttonhole")) {
                        query = "select item_no from trn_buttonhole where sl_no = '" + jtblLabourer.getValueAt(selected[j], 0) + "' and flag!='D' and year(date_created)='"+Global.year+"'";
                    }
                    rs = stmt.executeQuery(query);
                    if (rs.next()) {
                        item_no = rs.getInt(1);
                    }
                    query = "select stsl_no from mst_student where  order_no = '" + jtblLabourer.getValueAt(selected[j], 1) + "' and flag!='D' and year(date_created)='"+Global.year+"'";
                    rs = stmt.executeQuery(query);
                    if (rs.next()) {
                        stsl = rs.getInt(1);
                    }
                    query = "select a.item_no,sum(a.qty) from trn_stitching a join mst_item b on a.item_no = b.item_no where a.stsl_no = '" + stsl + "'  and b.buttonhole = '0' and a.item_no = '" + item_no + "' and a.status = 'C' and a.flag!='D' and b.flag!='D' and year(a.date_created)='"+Global.year+"' and year(b.date_created)='"+Global.year+"' group by a.item_no union "
                            + "select a.item_no,sum(a.qty) from trn_buttonhole a join mst_item b on a.item_no = b.item_no where a.stsl_no = '" + stsl + "' and b.buttonhole = '1' and a.item_no = '" + item_no + "' and a.status = 'C' and a.flag!='D' and b.flag!='D' and year(a.date_created)='"+Global.year+"' and year(b.date_created)='"+Global.year+"' group by a.item_no";
                    rs = stmt.executeQuery(query);
                    if (rs.next()) {
                        if (rs.getInt(2) >= Integer.parseInt(jtblLabourer.getValueAt(selected[j], 5).toString())) {
                            query = "select item_no,sum(qty) from trn_ironing where stsl_no = '" + stsl + "' and item_no ='" + item_no + "' and flag!='D' and year(date_created)='"+Global.year+"' group by item_no";
                            rs1 = stmt1.executeQuery(query);
                            if (rs1.next()) {
                                temp = rs.getInt(2) - rs1.getInt(2);
                                if (temp > 0) {
                                    if (temp >= Integer.parseInt(jtblLabourer.getValueAt(selected[j], 5).toString())) {
                                        query = "select sl_no,qty from trn_ironing where stsl_no ='" + stsl + "' and item_no = '" + rs.getString(1) + "' and date_given = '" + today + "' and iron_no = '" + ironno[0] + "' and status='P' and flag!='D' and year(date_created)='"+Global.year+"'";
                                        rs2 = stmt2.executeQuery(query);
                                        if (rs2.next()) {
                                            temp = Integer.parseInt(jtblLabourer.getValueAt(selected[j], 5).toString()) + rs2.getInt(2);
                                            query = "update trn_ironing set qty = '" + temp + "' where sl_no='" + rs2.getString(1) + "'";
                                            i = i + stmt2.executeUpdate(query);
                                        } else {
                                            query = "insert into trn_ironing(iron_no,stsl_no,item_no,qty,status,date_given,flag,date_created) values('" + ironno[0] + "','" + stsl + "','" + item_no + "','" + jtblLabourer.getValueAt(selected[j], 5).toString() + "','P','" + new SimpleDateFormat("yyyy-MM-dd").format(jdteDate1.getDate()) + "','I','" + today + "')";
                                            i = i + stmt2.executeUpdate(query);
                                        }
                                    }
                                }
                            } else {
                                query = "insert into trn_ironing(iron_no,stsl_no,item_no,qty,status,date_given,flag,date_created) values('" + ironno[0] + "','" + stsl + "','" + item_no + "','" + jtblLabourer.getValueAt(selected[j], 5).toString() + "','P','" + new SimpleDateFormat("yyyy-MM-dd").format(jdteDate1.getDate()) + "','I','" + today + "')";
                                i = i + stmt1.executeUpdate(query);
                            }
                        }
                    }
                }
                if (i > 0) {
                    con.commit();
                    JOptionPane.showMessageDialog(this, "Inserted Successfull!", "Info", JOptionPane.INFORMATION_MESSAGE);
                    populateIroningtable();
                    jdteDate1.setDate(null);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            } finally {
                try {
                    if (!rs.isClosed()) {
                        rs.close();
                    }
                    if (!rs1.isClosed()) {
                        rs1.close();
                    }
                    if (!rs2.isClosed()) {
                        rs2.close();
                    }
                    if (!con.isClosed()) {
                        con.close();
                    }
                    if (!stmt.isClosed()) {
                        stmt.isClosed();
                    }
                    if (!stmt1.isClosed()) {
                        stmt1.isClosed();
                    }
                    if (!stmt2.isClosed()) {
                        stmt2.isClosed();
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            }

        }
    }//GEN-LAST:event_jbtnGiveActionPerformed
    private void populateIroningtable() {
        try {
            rowcount = jtblIroningMaster.getRowCount();
            for (int i = 0; i < rowcount; i++) {
                model2.removeRow(0);
            }
            ironno = jcmbIroningMaster.getSelectedItem().toString().split("   ");
            con = new DBConnection().connect();
            stmt = con.createStatement();
            if (jdteDate1.getDate() == null) {
                query = "select a.sl_no,b.order_no,b.student_name,e.iron_name,d.item_name,a.qty,a.date_given,a.date_recieved,a.status from trn_ironing a left join mst_student b on a.stsl_no = b.stsl_no left join mst_item d on a.item_no = d.item_no left join mst_ironing e on a.iron_no = e.iron_no where a.iron_no = '" + ironno[0] + "' and b.school_no = '" + Global.getSchoolno() + "' and a.status = 'P' and a.flag!='D'  and b.flag!='D'  and d.flag!='D'  and e.flag!='D'";
            } else {
                query = "select a.sl_no,b.order_no,b.student_name,e.iron_name,d.item_name,a.qty,a.date_given,a.date_recieved,a.status from trn_ironing a left join mst_student b on a.stsl_no = b.stsl_no left join mst_item d on a.item_no = d.item_no left join mst_ironing e on a.iron_no = e.iron_no where a.iron_no = '" + ironno[0] + "' and b.school_no = '" + Global.getSchoolno() + "'  and a.date_given = '" + new SimpleDateFormat("yyyy-MM-dd").format(jdteDate1.getDate()) + "'  and a.status = 'P' and a.flag!='D'  and b.flag!='D'  and d.flag!='D'  and e.flag!='D'";
            }
            rs = stmt.executeQuery(query);
            while (rs.next()) {
                model2.addRow(new Object[]{});
                temp = jtblIroningMaster.getRowCount() - 1;
                jtblIroningMaster.setValueAt(rs.getString(1), temp, 0);
                jtblIroningMaster.setValueAt(rs.getString(2), temp, 1);
                jtblIroningMaster.setValueAt(rs.getString(3), temp, 2);
                jtblIroningMaster.setValueAt(rs.getString(4), temp, 3);
                jtblIroningMaster.setValueAt(rs.getString(5), temp, 4);
                jtblIroningMaster.setValueAt(rs.getString(6), temp, 5);
                jtblIroningMaster.setValueAt(rs.getString(7), temp, 6);
                jtblIroningMaster.setValueAt(rs.getString(8), temp, 7);
                jtblIroningMaster.setValueAt(rs.getString(9), temp, 8);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } finally {
            try {
                if (!rs.isClosed()) {
                    rs.close();
                }
                if (!con.isClosed()) {
                    con.close();
                }
                if (!stmt.isClosed()) {
                    stmt.isClosed();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }

    }

    private void populatetailortable() {
        try {
            rowcount = jtblLabourer.getRowCount();
            for (int i = 0; i < rowcount; i++) {
                model1.removeRow(0);
            }
            Labourerno = jcmbLabourer.getSelectedItem().toString().split("   ");
            con = new DBConnection().connect();
            stmt = con.createStatement();
            if (jcmbType.getSelectedItem().equals("Stitching")) {
                if (jdteDate.getDate() == null) {
                    query = "select a.sl_no,b.order_no,b.student_name,e.tailor_name,d.item_name,a.qty,a.date_given,a.date_recieved,a.status from trn_stitching a left join mst_student b on a.stsl_no = b.stsl_no left join mst_item d on a.item_no = d.item_no left join mst_tailor e on a.tailor_no = e.tailor_no where a.tailor_no = '" + Labourerno[0] + "' and b.school_no = '" + Global.getSchoolno() + "' and d.buttonhole = '0'  and a.status='C' and a.flag!='D'  and b.flag!='D'  and d.flag!='D'  and e.flag!='D'";
                } else {
                    query = "select a.sl_no,b.order_no,b.student_name,e.tailor_name,d.item_name,a.qty,a.date_given,a.date_recieved,a.status from trn_stitching a left join mst_student b on a.stsl_no = b.stsl_no left join mst_item d on a.item_no = d.item_no left join mst_tailor e on a.tailor_no = e.tailor_no where a.tailor_no = '" + Labourerno[0] + "' and b.school_no = '" + Global.getSchoolno() + "' and d.buttonhole = '0' and a.date_recieved = '" + new SimpleDateFormat("yyyy-MM-dd").format(jdteDate.getDate()) + "' and a.status='C' and a.flag!='D'  and b.flag!='D'  and d.flag!='D'  and e.flag!='D'";
                }
            } else if (jcmbType.getSelectedItem().equals("Buttonhole")) {
                if (jdteDate.getDate() == null) {
                    query = "select a.sl_no,b.order_no,b.student_name,e.bh_master_name,d.item_name,a.qty,a.date_given,a.date_recieved,a.status from trn_buttonhole a left join mst_student b on a.stsl_no = b.stsl_no left join mst_item d on a.item_no = d.item_no left join mst_buttonhole e on a.bh_no = e.bh_no where a.bh_no = '" + Labourerno[0] + "' and b.school_no = '" + Global.getSchoolno() + "' and a.status = 'C' and a.flag!='D' and b.flag!='D' and d.flag!='D' and e.flag!='D'";
                } else {
                    query = "select a.sl_no,b.order_no,b.student_name,e.bh_master_name,d.item_name,a.qty,a.date_given,a.date_recieved,a.status from trn_buttonhole a left join mst_student b on a.stsl_no = b.stsl_no left join mst_item d on a.item_no = d.item_no left join mst_buttonhole e on a.bh_no = e.bh_no where a.bh_no = '" + Labourerno[0] + "' and b.school_no = '" + Global.getSchoolno() + "' and a.date_recieved = '" + new SimpleDateFormat("yyyy-MM-dd").format(jdteDate.getDate()) + "' and a.status = 'C' and a.flag!='D' and b.flag!='D' and d.flag!='D' and e.flag!='D'";
                }
            }
            rs = stmt.executeQuery(query);
            while (rs.next()) {
                temp = jtblLabourer.getRowCount();
                model1.addRow(new Object[]{});
                jtblLabourer.setValueAt(rs.getString(1), temp, 0);
                jtblLabourer.setValueAt(rs.getString(2), temp, 1);
                jtblLabourer.setValueAt(rs.getString(3), temp, 2);
                jtblLabourer.setValueAt(rs.getString(4), temp, 3);
                jtblLabourer.setValueAt(rs.getString(5), temp, 4);
                jtblLabourer.setValueAt(rs.getString(6), temp, 5);
                jtblLabourer.setValueAt(rs.getString(7), temp, 6);
                jtblLabourer.setValueAt(rs.getString(8), temp, 7);
                jtblLabourer.setValueAt(rs.getString(9), temp, 8);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } finally {
            try {
                if (!rs.isClosed()) {
                    rs.close();
                }
                if (!con.isClosed()) {
                    con.close();
                }
                if (!stmt.isClosed()) {
                    stmt.isClosed();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnGive;
    private javax.swing.JButton jbtnView;
    private javax.swing.JComboBox jcmbIroningMaster;
    private javax.swing.JComboBox jcmbLabourer;
    private javax.swing.JComboBox jcmbType;
    private com.toedter.calendar.JDateChooser jdteDate;
    private com.toedter.calendar.JDateChooser jdteDate1;
    private javax.swing.JTable jtblIroningMaster;
    private javax.swing.JTable jtblLabourer;
    // End of variables declaration//GEN-END:variables
}
