/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rose;

import java.awt.Font;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Betsy
 */
public class JIFraMViewStudentItemDetail extends javax.swing.JInternalFrame {

    Connection con;
    Statement stmt1, stmt2;
    ResultSet rs1, rs2;
    String query, classno;
    String[] schoolno;
    MyTableModel model1;
    int stsl = 0, rowcount = 0, slno = 0, total = 0;
    float gt = 0, material_total = 0, item_total = 0;
    Vector<String> column;
    String temp;
    String today = new SimpleDateFormat("dd-MM-yy").format(new Date());
     

    public JIFraMViewStudentItemDetail() {
        try {
            initComponents();
            column = new Vector<>();
            //jtblStudent.setModel(model1);
            jcmbGender.addItem("");
            jcmbGender.addItem("Male");
            jcmbGender.addItem("Female");
            con = new DBConnection().connect();
            stmt1 = con.createStatement();
            query = "select school_no,school_name from mst_school where flag !='D' and year(date_created)='" + Global.year + "'";
            rs1 = stmt1.executeQuery(query);
            jcmbSchool.removeAllItems();
            jcmbSchool.addItem("");
            while (rs1.next()) {
                jcmbSchool.addItem(rs1.getString(1) + "   " + rs1.getString(2));
            }

            jcmbFontSize.setSelectedItem("14");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } finally {
            try {
                if (!rs1.isClosed()) {
                    rs1.close();
                }
                if (!con.isClosed()) {
                    con.close();
                }
                if (!stmt1.isClosed()) {
                    stmt1.isClosed();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcmbClass = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jcmbGender = new javax.swing.JComboBox();
        jbtnView = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblStudent = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jcmbFontSize = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jcmbDivision = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jcmbSchool = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jcmbDateCreated = new javax.swing.JComboBox();

        setClosable(true);
        setTitle("View All Student Item Detail");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setText("Class");

        jcmbClass.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbClassItemStateChanged(evt);
            }
        });

        jLabel3.setText("Gender");

        jbtnView.setText("View");
        jbtnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnViewActionPerformed(evt);
            }
        });

        jtblStudent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtblStudent);

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Font Size");

        jcmbFontSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "8", "10", "12", "14", "16", "18", "20", "22", "24", "26", " ", " " }));

        jLabel4.setText("Division");

        jLabel5.setText("School Name :");

        jcmbSchool.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbSchoolItemStateChanged(evt);
            }
        });

        jLabel6.setText("Date Created");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcmbClass, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcmbDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcmbDateCreated, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcmbFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jbtnView)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcmbSchool, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcmbSchool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jcmbFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jcmbDateCreated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnView)
                        .addComponent(jLabel2)
                        .addComponent(jcmbClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jButton1)
                        .addComponent(jLabel4)
                        .addComponent(jcmbDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcmbClassItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbClassItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (jcmbClass.getSelectedItem() != null && !jcmbClass.getSelectedItem().equals("")) {
                try {
                    con = new DBConnection().connect();
                    stmt1 = con.createStatement();
                    query = "select distinct(a.division) from mst_student a join mst_class b on a.class_no = b.class_no where b.class = '" + jcmbClass.getSelectedItem() + "' and a.school_no = '" + schoolno[0] + "' and a.flag!='D' and b.flag!='D'";
                    rs1 = stmt1.executeQuery(query);
                    jcmbDivision.addItem("");
                    while (rs1.next()) {
                        jcmbDivision.addItem(rs1.getString(1));
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                } finally {
                    try {
                        if (!rs1.isClosed()) {
                            rs1.close();
                        }
                        if (!con.isClosed()) {
                            con.close();
                        }
                        if (!stmt1.isClosed()) {
                            stmt1.isClosed();
                        }
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage());
                    }
                }
            } else {
                jcmbDivision.removeAllItems();
            }
        }
    }//GEN-LAST:event_jcmbClassItemStateChanged
    class MyTableModel extends DefaultTableModel {

        public MyTableModel(Vector rowData, int rowCount) {
            super(rowData, rowCount);
        }

        @Override
        public Class getColumnClass(int col) {
            if (col == 2 || col == 4) //second column accepts only Integer values  
            {
                return String.class;  //other columns accept String values                  
            } else {
                return Integer.class;
            }
        }

        @Override
        public boolean isCellEditable(int row, int col) {
            return false;
        }
    }
    private void jbtnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnViewActionPerformed
        if (jcmbSchool.getSelectedItem() == null || jcmbSchool.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(this, "Please select a school", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            schoolno = jcmbSchool.getSelectedItem().toString().split("   ");
            rowcount = jtblStudent.getRowCount();
            jtblStudent.setFont(new Font("Tahoma", Font.PLAIN, Integer.parseInt(jcmbFontSize.getSelectedItem().toString())));
            jtblStudent.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, Integer.parseInt(jcmbFontSize.getSelectedItem().toString())));
            jtblStudent.setRowHeight(Integer.parseInt(jcmbFontSize.getSelectedItem().toString()) + 5);
            for (int i = 0; i < rowcount; i++) {
                model1.removeRow(0);
            }
            column.clear();
            model1 = new MyTableModel(column, 0);
            classno = "";
            try {
                con = new DBConnection().connect();
                stmt1 = con.createStatement();
                query = "select class_no from mst_class where class='" + jcmbClass.getSelectedItem() + "'";
                rs1 = stmt1.executeQuery(query);
                if (rs1.next()) {
                    classno = rs1.getString(1);
                }
                if (jcmbDateCreated.getSelectedItem() != null && !jcmbDateCreated.getSelectedItem().equals("")) {
                    if (jcmbDivision.getSelectedItem() != null && !jcmbDivision.getSelectedItem().equals("")) {
                        if ((jcmbClass.getSelectedItem() == null || jcmbClass.getSelectedItem().equals("")) && (jcmbGender.getSelectedItem() == null || jcmbGender.getSelectedItem().equals(""))) {
                            generatetable("select a.stsl_no,a.order_no,a.student_name,b.class,a.division from mst_student a join mst_class b on a.class_no = b.class_no where a.school_no = '" + schoolno[0] + "' and a.date_created = '" + jcmbDateCreated.getSelectedItem() + "' and a.division = '" + jcmbDivision.getSelectedItem() + "' and a.flag != 'D' and b.flag != 'D'", "All", null);
                        } else if ((jcmbClass.getSelectedItem() != null || !jcmbClass.getSelectedItem().equals("")) && (jcmbGender.getSelectedItem() == null || jcmbGender.getSelectedItem().equals(""))) {
                            //CLASS
                            generatetable("select a.stsl_no,a.order_no,a.student_name,b.class,a.division from mst_student a join mst_class b on a.class_no = b.class_no where a.school_no = '" + schoolno[0] + "' and a.date_created = '" + jcmbDateCreated.getSelectedItem() + "' and a.division = '" + jcmbDivision.getSelectedItem() + "' and a.class_no = '" + classno + "' and a.flag != 'D' and b.flag != 'D'", "All", jcmbClass.getSelectedItem().toString());
                        } else if ((jcmbClass.getSelectedItem() == null || jcmbClass.getSelectedItem().equals("")) && (jcmbGender.getSelectedItem() != null || !jcmbGender.getSelectedItem().equals(""))) {
                            //Gender
                            generatetable("select a.stsl_no,a.order_no,a.student_name,b.class,a.division from mst_student a join mst_class b on a.class_no = b.class_no where a.school_no = '" + schoolno[0] + "' and a.date_created = '" + jcmbDateCreated.getSelectedItem() + "' and a.division = '" + jcmbDivision.getSelectedItem() + "' and a.gender = '" + jcmbGender.getSelectedItem() + "' and a.flag != 'D' and b.flag != 'D'", jcmbGender.getSelectedItem().toString(), null);
                        } else if ((jcmbClass.getSelectedItem() != null || !jcmbClass.getSelectedItem().equals("")) && (jcmbGender.getSelectedItem() != null || !jcmbGender.getSelectedItem().equals(""))) {
                            //CLASS
                            //Gender
                            generatetable("select a.stsl_no,a.order_no,a.student_name,b.class,a.division from mst_student a join mst_class b on a.class_no = b.class_no where a.school_no = '" + schoolno[0] + "' and a.date_created = '" + jcmbDateCreated.getSelectedItem() + "' and a.division = '" + jcmbDivision.getSelectedItem() + "' and a.class_no = '" + classno + "' and a.gender = '" + jcmbGender.getSelectedItem() + "' and a.flag != 'D' and b.flag != 'D'", jcmbGender.getSelectedItem().toString(), jcmbClass.getSelectedItem().toString());
                        }
                    } else {
                        if ((jcmbClass.getSelectedItem() == null || jcmbClass.getSelectedItem().equals("")) && (jcmbGender.getSelectedItem() == null || jcmbGender.getSelectedItem().equals(""))) {
                            generatetable("select a.stsl_no,a.order_no,a.student_name,b.class,a.division from mst_student a join mst_class b on a.class_no = b.class_no where school_no = '" + schoolno[0] + "' and a.date_created = '" + jcmbDateCreated.getSelectedItem() + "' and a.flag != 'D' and b.flag != 'D'", "All", null);
                        } else if ((jcmbClass.getSelectedItem() != null || !jcmbClass.getSelectedItem().equals("")) && (jcmbGender.getSelectedItem() == null || jcmbGender.getSelectedItem().equals(""))) {
                            //CLASS
                            generatetable("select a.stsl_no,a.order_no,a.student_name,b.class,a.division from mst_student a join mst_class b on a.class_no = b.class_no where school_no = '" + schoolno[0] + "' and a.date_created = '" + jcmbDateCreated.getSelectedItem() + "' and a.class_no = '" + classno + "' and a.flag != 'D' and b.flag != 'D'", "All", jcmbClass.getSelectedItem().toString());
                        } else if ((jcmbClass.getSelectedItem() == null || jcmbClass.getSelectedItem().equals("")) && (jcmbGender.getSelectedItem() != null || !jcmbGender.getSelectedItem().equals(""))) {
                            //Gender
                            generatetable("select a.stsl_no,a.order_no,a.student_name,b.class,a.division from mst_student a join mst_class b on a.class_no = b.class_no where school_no = '" + schoolno[0] + "' and a.date_created = '" + jcmbDateCreated.getSelectedItem() + "' and a.gender = '" + jcmbGender.getSelectedItem() + "' and a.flag != 'D' and b.flag != 'D'", jcmbGender.getSelectedItem().toString(), null);
                        } else if ((jcmbClass.getSelectedItem() != null || !jcmbClass.getSelectedItem().equals("")) && (jcmbGender.getSelectedItem() != null || !jcmbGender.getSelectedItem().equals(""))) {
                            //CLASS
                            //Gender
                            generatetable("select a.stsl_no,a.order_no,a.student_name,b.class,a.division from mst_student a join mst_class b on a.class_no = b.class_no where school_no = '" + schoolno[0] + "' and a.date_created = '" + jcmbDateCreated.getSelectedItem() + "' and a.class_no = '" + classno + "' and a.gender = '" + jcmbGender.getSelectedItem() + "' and a.flag != 'D' and b.flag != 'D'", jcmbGender.getSelectedItem().toString(), jcmbClass.getSelectedItem().toString());
                        }
                    }
                } else {
                    if (jcmbDivision.getSelectedItem() != null && !jcmbDivision.getSelectedItem().equals("")) {
                        if ((jcmbClass.getSelectedItem() == null || jcmbClass.getSelectedItem().equals("")) && (jcmbGender.getSelectedItem() == null || jcmbGender.getSelectedItem().equals(""))) {
                            generatetable("select a.stsl_no,a.order_no,a.student_name,b.class,a.division from mst_student a join mst_class b on a.class_no = b.class_no where a.school_no = '" + schoolno[0] + "' and a.division = '" + jcmbDivision.getSelectedItem() + "' and a.flag != 'D' and b.flag != 'D'", "All", null);
                        } else if ((jcmbClass.getSelectedItem() != null || !jcmbClass.getSelectedItem().equals("")) && (jcmbGender.getSelectedItem() == null || jcmbGender.getSelectedItem().equals(""))) {
                            //CLASS
                            generatetable("select a.stsl_no,a.order_no,a.student_name,b.class,a.division from mst_student a join mst_class b on a.class_no = b.class_no where a.school_no = '" + schoolno[0] + "' and a.division = '" + jcmbDivision.getSelectedItem() + "' and a.class_no = '" + classno + "' and a.flag != 'D' and b.flag != 'D'", "All", jcmbClass.getSelectedItem().toString());
                        } else if ((jcmbClass.getSelectedItem() == null || jcmbClass.getSelectedItem().equals("")) && (jcmbGender.getSelectedItem() != null || !jcmbGender.getSelectedItem().equals(""))) {
                            //Gender
                            generatetable("select a.stsl_no,a.order_no,a.student_name,b.class,a.division from mst_student a join mst_class b on a.class_no = b.class_no where a.school_no = '" + schoolno[0] + "' and a.division = '" + jcmbDivision.getSelectedItem() + "' and a.gender = '" + jcmbGender.getSelectedItem() + "' and a.flag != 'D' and b.flag != 'D'", jcmbGender.getSelectedItem().toString(), null);
                        } else if ((jcmbClass.getSelectedItem() != null || !jcmbClass.getSelectedItem().equals("")) && (jcmbGender.getSelectedItem() != null || !jcmbGender.getSelectedItem().equals(""))) {
                            //CLASS
                            //Gender
                            generatetable("select a.stsl_no,a.order_no,a.student_name,b.class,a.division from mst_student a join mst_class b on a.class_no = b.class_no where a.school_no = '" + schoolno[0] + "' and a.division = '" + jcmbDivision.getSelectedItem() + "' and a.class_no = '" + classno + "' and a.gender = '" + jcmbGender.getSelectedItem() + "' and a.flag != 'D' and b.flag != 'D'", jcmbGender.getSelectedItem().toString(), jcmbClass.getSelectedItem().toString());
                        }
                    } else {
                        if ((jcmbClass.getSelectedItem() == null || jcmbClass.getSelectedItem().equals("")) && (jcmbGender.getSelectedItem() == null || jcmbGender.getSelectedItem().equals(""))) {
                            generatetable("select a.stsl_no,a.order_no,a.student_name,b.class,a.division from mst_student a join mst_class b on a.class_no = b.class_no where school_no = '" + schoolno[0] + "' and a.flag != 'D' and b.flag != 'D'", "All", null);
                        } else if ((jcmbClass.getSelectedItem() != null || !jcmbClass.getSelectedItem().equals("")) && (jcmbGender.getSelectedItem() == null || jcmbGender.getSelectedItem().equals(""))) {
                            //CLASS
                            generatetable("select a.stsl_no,a.order_no,a.student_name,b.class,a.division from mst_student a join mst_class b on a.class_no = b.class_no where school_no = '" + schoolno[0] + "' and a.class_no = '" + classno + "' and a.flag != 'D' and b.flag != 'D'", "All", jcmbClass.getSelectedItem().toString());
                        } else if ((jcmbClass.getSelectedItem() == null || jcmbClass.getSelectedItem().equals("")) && (jcmbGender.getSelectedItem() != null || !jcmbGender.getSelectedItem().equals(""))) {
                            //Gender
                            generatetable("select a.stsl_no,a.order_no,a.student_name,b.class,a.division from mst_student a join mst_class b on a.class_no = b.class_no where school_no = '" + schoolno[0] + "' and a.gender = '" + jcmbGender.getSelectedItem() + "' and a.flag != 'D' and b.flag != 'D'", jcmbGender.getSelectedItem().toString(), null);
                        } else if ((jcmbClass.getSelectedItem() != null || !jcmbClass.getSelectedItem().equals("")) && (jcmbGender.getSelectedItem() != null || !jcmbGender.getSelectedItem().equals(""))) {
                            //CLASS
                            //Gender
                            generatetable("select a.stsl_no,a.order_no,a.student_name,b.class,a.division from mst_student a join mst_class b on a.class_no = b.class_no where school_no = '" + schoolno[0] + "' and a.class_no = '" + classno + "' and a.gender = '" + jcmbGender.getSelectedItem() + "' and a.flag != 'D' and b.flag != 'D'", jcmbGender.getSelectedItem().toString(), jcmbClass.getSelectedItem().toString());
                        }
                    }
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            } finally {
                try {
                    if (!rs1.isClosed()) {
                        rs1.close();
                    }
                    if (!con.isClosed()) {
                        con.close();
                    }
                    if (!stmt1.isClosed()) {
                        stmt1.isClosed();
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            }
        }

    }//GEN-LAST:event_jbtnViewActionPerformed
    private void generatetable(String mainquery, String Gender, String c) {
        try {
            column.add("Sl.");
            column.add("ONo.");
            column.add("Name");
            column.add("Class");
            column.add("Div");
            con = new DBConnection().connect();
            stmt1 = con.createStatement();
            stmt2 = con.createStatement();
            if (Gender.equals("All") && c == null) {
                query = "select a.item_no,b.item_name from mst_school_item_price a join mst_item b on a.item_no = b.item_no where a.school_no = '" + schoolno[0] + "' and a.flag!='D' and b.flag!='D' order by b.item_name";
            } else if (Gender.equals("All") && c != null) {
                query = "select a.item_no,b.item_name from mst_school_item_price a join mst_item b on a.item_no = b.item_no where a.school_no = '" + schoolno[0] + "' and a.class_from <= '" + c + "' and a.class_to >='" + c + "' and a.flag!='D' and b.flag!='D' order by b.item_name";
            } else if (!Gender.equals("All") && c == null) {
                if (Gender.equals("Female")) {
                    query = "select a.item_no,b.item_name from mst_school_item_price a join mst_item b on a.item_no = b.item_no where a.school_no = '" + schoolno[0] + "' and b.gender in ('Female','Common') and a.flag!='D' and b.flag!='D' order by b.item_name";
                } else if (Gender.equals("Male")) {
                    query = "select a.item_no,b.item_name from mst_school_item_price a join mst_item b on a.item_no = b.item_no where a.school_no = '" + schoolno[0] + "' and b.gender in ('Male','Common') and a.flag!='D' and b.flag!='D' order by b.item_name";
                }
            } else if (!Gender.equals("All") && c != null) {
                if (Gender.equals("Female")) {
                    query = "select a.item_no,b.item_name from mst_school_item_price a join mst_item b on a.item_no = b.item_no where a.school_no = '" + schoolno[0] + "' and b.gender in ('Female','Common') and a.class_from <= '" + c + "' and a.class_to >='" + c + "' and a.flag!='D' and b.flag!='D' order by b.item_name";
                } else if (Gender.equals("Male")) {
                    query = "select a.item_no,b.item_name from mst_school_item_price a join mst_item b on a.item_no = b.item_no where a.school_no = '" + schoolno[0] + "' and b.gender in ('Male','Common') and a.class_from <= '" + c + "' and a.class_to >='" + c + "' and a.flag!='D' and b.flag!='D' order by b.item_name";
                }
            }
            rs1 = stmt1.executeQuery(query);
            for (int i = 0; rs1.next(); i++) {
                column.add(rs1.getString(2));
            }
            model1 = new MyTableModel(column, 0);
            jtblStudent.setAutoCreateRowSorter(true);
            jtblStudent.setModel(model1);
            DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
            rightRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
            jtblStudent.getTableHeader().setDefaultRenderer(rightRenderer);
            jtblStudent.getColumn(jtblStudent.getColumnName(0)).setCellRenderer(rightRenderer);
            jtblStudent.getColumn(jtblStudent.getColumnName(1)).setCellRenderer(rightRenderer);
            jtblStudent.getColumn(jtblStudent.getColumnName(2)).setCellRenderer(rightRenderer);
            jtblStudent.getColumn(jtblStudent.getColumnName(3)).setCellRenderer(rightRenderer);
            jtblStudent.getColumn(jtblStudent.getColumnName(4)).setCellRenderer(rightRenderer);
            jtblStudent.setShowGrid(true);
            query = mainquery;
            slno = 1;
            rs1 = stmt1.executeQuery(query);
            jtblStudent.getColumnModel().getColumn(0).setPreferredWidth(30);
            jtblStudent.getColumnModel().getColumn(1).setPreferredWidth(50);
            jtblStudent.getColumnModel().getColumn(2).setPreferredWidth(150);
            jtblStudent.getColumnModel().getColumn(3).setPreferredWidth(40);
            jtblStudent.getColumnModel().getColumn(4).setPreferredWidth(30);
            for (int i = 0; rs1.next(); i++) {
                stsl = rs1.getInt(1);
                model1.addRow(new Object[]{});
                jtblStudent.setValueAt(slno, model1.getRowCount() - 1, 0);
                jtblStudent.setValueAt(rs1.getString(2), model1.getRowCount() - 1, 1);
                jtblStudent.setValueAt(rs1.getString(3), model1.getRowCount() - 1, 2);
                jtblStudent.setValueAt(rs1.getString(4), model1.getRowCount() - 1, 3);
                jtblStudent.setValueAt(rs1.getString(5), model1.getRowCount() - 1, 4);
                slno++;
                query = "select b.item_name,a.qty from mst_student_detail a join mst_item b on a.item_no = b.item_no where stsl_no = '" + stsl + "' and a.flag!='D' and b.flag!='D'";
                rs2 = stmt2.executeQuery(query);
                while (rs2.next()) {
                    for (int j = 5; j < column.size(); j++) {
                        if (column.get(j).equals(rs2.getString(1))) {
                            jtblStudent.setValueAt(rs2.getInt(2), model1.getRowCount() - 1, j);
                            jtblStudent.getColumnModel().getColumn(j).setPreferredWidth(100);
                            jtblStudent.getColumn(jtblStudent.getColumnName(j)).setCellRenderer(rightRenderer);
                        } else {
                            //jtblStudent.setValueAt("-", jtblStudent.getRowCount() - 1, j);
                        }
                    }
                }
            }
            model1.addRow(new Object[]{});
            model1.addRow(new Object[]{});
            jtblStudent.setValueAt("TOTAL", model1.getRowCount() - 1, 2);
            for (int j = 5; j < column.size(); j++) {
                total = 0;
                for (int k = 0; k < jtblStudent.getRowCount() - 2; k++) {
                    if (jtblStudent.getValueAt(k, j) != null) {
                        total = total + Integer.parseInt(jtblStudent.getValueAt(k, j).toString());
                    }
                }
                jtblStudent.setValueAt(total, jtblStudent.getRowCount() - 1, j);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } finally {
            try {
                if (!rs1.isClosed()) {
                    rs1.close();
                }
                if (!con.isClosed()) {
                    con.close();
                }
                if (!stmt1.isClosed()) {
                    stmt1.isClosed();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jtblStudent.getRowCount() > 0) {
            MessageFormat header = new MessageFormat("Student Item Detail - " + Global.getSchoolname() + "  " + today);
            MessageFormat footer = new MessageFormat("Page {0,number,integer}");
            try {
                jtblStudent.print(JTable.PrintMode.FIT_WIDTH, header, footer);

            } catch (java.awt.print.PrinterException e) {
                System.err.format("Cannot print %s%n", e.getMessage());

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcmbSchoolItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbSchoolItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (jcmbSchool.getSelectedItem() == null || jcmbSchool.getSelectedItem().equals("")) {
                jcmbClass.removeAllItems();
            } else {
                try {
                    schoolno = jcmbSchool.getSelectedItem().toString().split("   ");
                    con = new DBConnection().connect();
                    stmt1 = con.createStatement();
                    query = "select distinct(a.class_no),b.class from mst_student a join mst_class b on a.class_no = b.class_no where a.flag != 'D' and b.flag != 'D' and school_no = '" + schoolno[0] + "' ";
                    rs1 = stmt1.executeQuery(query);
                    jcmbClass.removeAllItems();
                    jcmbClass.addItem("");
                    while (rs1.next()) {
                        jcmbClass.addItem(rs1.getString(2));
                    }
                    query = "select distinct(date_created) from mst_student where flag != 'D' and school_no = '" + schoolno[0] + "' ";
                    rs1 = stmt1.executeQuery(query);
                    jcmbDateCreated.removeAllItems();
                    jcmbDateCreated.addItem("");
                    while (rs1.next()) {
                        jcmbDateCreated.addItem(rs1.getString(1));
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                } finally {
                    try {
                        if (!rs1.isClosed()) {
                            rs1.close();
                        }
                        if (!con.isClosed()) {
                            con.close();
                        }
                        if (!stmt1.isClosed()) {
                            stmt1.isClosed();
                        }
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage());
                    }
                }
            }
        }
    }//GEN-LAST:event_jcmbSchoolItemStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnView;
    private javax.swing.JComboBox jcmbClass;
    private javax.swing.JComboBox jcmbDateCreated;
    private javax.swing.JComboBox jcmbDivision;
    private javax.swing.JComboBox jcmbFontSize;
    private javax.swing.JComboBox jcmbGender;
    private javax.swing.JComboBox jcmbSchool;
    private javax.swing.JTable jtblStudent;
    // End of variables declaration//GEN-END:variables
}
