/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rose;

import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Betsy
 */
public class JIFraEditWage extends javax.swing.JInternalFrame {

    DefaultTableModel model;
    Connection con = null;
    ResultSet rs = null;
    Statement stmt = null;
    String query;
    String[] LabourerNo;
    Double total;
    int rowcount, temp, slno;
    String today = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
    String text;
     

    public JIFraEditWage() {
        initComponents();
        jcmbType.addItem("Cutting");
        jcmbType.addItem("Stitching");
        jdteDate.setDate(new Date());
        model = (DefaultTableModel) jtblWageAdvance.getModel();
        slno = 0;
    }

    private void populatestitching() {
        try {
            slno = 0;
            LabourerNo = jcmbName.getSelectedItem().toString().split("   ");
            con = new DBConnection().connect();
            con.setAutoCommit(false);
            stmt = con.createStatement();
            rowcount = jtblWageAdvance.getRowCount();
            for (int i = 0; i < rowcount; i++) {
                model.removeRow(0);
            }
            int j = 0;
            query = "select a.sl_no,a.labour_type,b.tailor_name,a.description,a.date_given,a.amount from mst_wage a join mst_tailor b on a.labour_no = b.tailor_no  where a.labour_type= 'Stitching' and b.tailor_no = '" + LabourerNo[0] + "' and a.flag!='D' and b.flag!='D' order by a.sl_no desc";
            rs = stmt.executeQuery(query);
            for (j = 0; rs.next(); j++) {
                model.addRow(new Object[]{""});
                jtblWageAdvance.setValueAt(rs.getString(1), j, 0);
                jtblWageAdvance.setValueAt(rs.getString(2), j, 1);
                jtblWageAdvance.setValueAt(rs.getString(3), j, 2);
                jtblWageAdvance.setValueAt(rs.getString(4), j, 3);
                jtblWageAdvance.setValueAt(rs.getString(5), j, 4);
                jtblWageAdvance.setValueAt(rs.getString(6), j, 5);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } finally {
            try {
                if (!rs.isClosed()) {
                    rs.close();
                }
                if (!con.isClosed()) {
                    con.close();
                }
                if (!stmt.isClosed()) {
                    stmt.isClosed();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }

    private void populatecutting() {
        try {
            LabourerNo = jcmbName.getSelectedItem().toString().split("   ");
            con = new DBConnection().connect();
            con.setAutoCommit(false);
            stmt = con.createStatement();
            rowcount = jtblWageAdvance.getRowCount();
            for (int i = 0; i < rowcount; i++) {
                model.removeRow(0);
            }
            int j = 0;
            query = "select a.sl_no,a.labour_type,b.cutting_master,a.description,a.date_given,a.amount from mst_wage a join mst_group b on a.labour_no = b.group_no  where a.labour_type= 'Cutting' and b.group_no = '" + LabourerNo[0] + "' and a.flag!='D' and b.flag!='D' order by a.sl_no desc";
            rs = stmt.executeQuery(query);
            for (j = 0; rs.next(); j++) {
                model.addRow(new Object[]{""});
                jtblWageAdvance.setValueAt(rs.getString(1), j, 0);
                jtblWageAdvance.setValueAt(rs.getString(2), j, 1);
                jtblWageAdvance.setValueAt(rs.getString(3), j, 2);
                jtblWageAdvance.setValueAt(rs.getString(4), j, 3);
                jtblWageAdvance.setValueAt(rs.getString(5), j, 4);
                jtblWageAdvance.setValueAt(rs.getString(6), j, 5);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } finally {
            try {
                if (!rs.isClosed()) {
                    rs.close();
                }
                if (!con.isClosed()) {
                    con.close();
                }
                if (!stmt.isClosed()) {
                    stmt.isClosed();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblWageAdvance = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jcmbType = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jcmbName = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jdteDate = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jtxtAmount = new javax.swing.JTextField();
        jbtnEdit = new javax.swing.JButton();
        jbtnSave = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtxtDescription = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Edit Wage");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jtblWageAdvance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Type", "Name", "Description", "Date", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblWageAdvance);
        jtblWageAdvance.getColumnModel().getColumn(0).setMinWidth(0);
        jtblWageAdvance.getColumnModel().getColumn(0).setPreferredWidth(0);
        jtblWageAdvance.getColumnModel().getColumn(0).setMaxWidth(0);

        jLabel1.setText("Type");

        jcmbType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbTypeItemStateChanged(evt);
            }
        });

        jLabel2.setText("Name");

        jcmbName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbNameItemStateChanged(evt);
            }
        });

        jLabel3.setText("Date");

        jLabel4.setText("Amount");

        jtxtAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtAmountKeyPressed(evt);
            }
        });

        jbtnEdit.setText("Edit");
        jbtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditActionPerformed(evt);
            }
        });

        jbtnSave.setText("Save");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });

        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        jLabel5.setText("Description");

        jtxtDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtDescriptionKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnDelete))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcmbName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtnSave)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jdteDate, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jcmbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnEdit)
                    .addComponent(jbtnDelete))
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jdteDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jtxtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jtxtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnSave)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcmbTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbTypeItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            try {
                con = new DBConnection().connect();
                stmt = con.createStatement();
                if (jcmbType.getSelectedItem().equals("Cutting")) {
                    query = "select group_no,cutting_master from mst_group where flag!='D' and year(date_created)='" + Global.year + "'";
                    rs = stmt.executeQuery(query);
                    jcmbName.removeAllItems();
                    jcmbName.addItem("");
                    while (rs.next()) {
                        jcmbName.addItem(rs.getString(1) + "   " + rs.getString(2));
                    }
                } else if (jcmbType.getSelectedItem().equals("Stitching")) {
                    query = "select tailor_no,tailor_name from mst_tailor where flag!='D' and year(date_created)='" + Global.year + "'";
                    rs = stmt.executeQuery(query);
                    jcmbName.removeAllItems();
                    jcmbName.addItem("");
                    while (rs.next()) {
                        jcmbName.addItem(rs.getString(1) + "   " + rs.getString(2));
                    }
                } else {
                    jcmbName.removeAllItems();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            } finally {
                try {
                    if (!rs.isClosed()) {
                        rs.close();
                    }
                    if (!con.isClosed()) {
                        con.close();
                    }
                    if (!stmt.isClosed()) {
                        stmt.isClosed();
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            }

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbTypeItemStateChanged

    private void jcmbNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbNameItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (jcmbType.getSelectedItem().equals("Cutting") && !jcmbName.getSelectedItem().equals("")) {
                populatecutting();
            } else if (jcmbType.getSelectedItem().equals("Stitching") && !jcmbName.getSelectedItem().equals("")) {
                populatestitching();
            }
        }
    }//GEN-LAST:event_jcmbNameItemStateChanged

    private void jtxtAmountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtAmountKeyPressed
        text = "";
        text = jtxtAmount.getText();
        if (text.length() == 5) {
            jtxtAmount.setEditable(false);
            if (evt.getKeyChar() == evt.VK_BACK_SPACE || evt.getKeyChar() == evt.VK_DELETE || evt.getKeyChar() == evt.VK_LEFT || evt.getKeyChar() == evt.VK_RIGHT) {
                jtxtAmount.setEditable(true);
            }
        } else if (evt.getKeyChar() >= evt.VK_0 && evt.getKeyChar() <= evt.VK_9 || evt.getKeyChar() == evt.VK_BACK_SPACE || evt.getKeyChar() == evt.VK_DELETE || evt.getKeyChar() == evt.VK_LEFT || evt.getKeyChar() == evt.VK_RIGHT || evt.getKeyChar() == evt.VK_PERIOD) {
            jtxtAmount.setEditable(true);
        } else {
            jtxtAmount.setEditable(false);
        }
    }//GEN-LAST:event_jtxtAmountKeyPressed

    private void jbtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditActionPerformed
        if (jtblWageAdvance.getSelectedRow() != -1) {
            try {
                slno = Integer.parseInt(jtblWageAdvance.getValueAt(jtblWageAdvance.getSelectedRow(), 0).toString());
                jtxtAmount.setText(jtblWageAdvance.getValueAt(jtblWageAdvance.getSelectedRow(), 5).toString());
                jtxtDescription.setText(jtblWageAdvance.getValueAt(jtblWageAdvance.getSelectedRow(), 3).toString());
                jdteDate.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(jtblWageAdvance.getValueAt(jtblWageAdvance.getSelectedRow(), 4).toString()));
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_jbtnEditActionPerformed

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        if (slno == 0) {
            JOptionPane.showMessageDialog(this, "Please select a record to update", "Select", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtxtAmount.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter an amount", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else if (jdteDate.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please enter a date", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtxtDescription.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter a description", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                con = new DBConnection().connect();
                stmt = con.createStatement();
                query = "UPDATE mst_wage SET DESCRIPTION = '" + jtxtDescription.getText().trim() + "',AMOUNT ='" + jtxtAmount.getText().trim() + "', DATE_GIVEN ='" + new SimpleDateFormat("yyyy-MM-dd").format(jdteDate.getDate()) + "', FLAG='U',DATE_UPDATED='" + today + "' WHERE SL_NO='" + slno + "'";
                int i = stmt.executeUpdate(query);
                if (i > 0) {
                    JOptionPane.showMessageDialog(this, "Update successfull!", "Info", JOptionPane.INFORMATION_MESSAGE);
                    slno = 0;
                    if (jcmbType.getSelectedItem().equals("Cutting") && !jcmbName.getSelectedItem().equals("")) {
                        populatecutting();
                    } else if (jcmbType.getSelectedItem().equals("Stitching") && !jcmbName.getSelectedItem().equals("")) {
                        populatestitching();
                    }
                    jtxtAmount.setText("");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            } finally {
                try {
                    if (!con.isClosed()) {
                        con.close();
                    }
                    if (!stmt.isClosed()) {
                        stmt.isClosed();
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        if (slno != 0) {
            JOptionPane.showMessageDialog(this, "Please complete the update before deleting", "Select", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtblWageAdvance.getSelectedRow() > -1) {
            try {
                int b = JOptionPane.showConfirmDialog(this, "Do you want delete the record?", "Confirm", JOptionPane.YES_NO_OPTION);
                if (b == JOptionPane.YES_OPTION) {
                    slno = Integer.parseInt(jtblWageAdvance.getValueAt(jtblWageAdvance.getSelectedRow(), 0).toString());
                    con = new DBConnection().connect();
                    stmt = con.createStatement();
                    query = "UPDATE mst_wage SET FLAG='D',DATE_UPDATED='" + today + "' WHERE SL_NO='" + slno + "'";
                    int i = stmt.executeUpdate(query);
                    if (i > 0) {
                        JOptionPane.showMessageDialog(this, "Delete successfull!", "Info", JOptionPane.INFORMATION_MESSAGE);
                        if (jcmbType.getSelectedItem().equals("Cutting") && !jcmbName.getSelectedItem().equals("")) {
                            populatecutting();
                        } else if (jcmbType.getSelectedItem().equals("Stitching") && !jcmbName.getSelectedItem().equals("")) {
                            populatestitching();
                        }
                        jtxtAmount.setText("");
                        jtxtDescription.setText("");
                    }
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            } finally {
                try {
                    if (!con.isClosed()) {
                        con.close();
                    }
                    if (!stmt.isClosed()) {
                        stmt.isClosed();
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jtxtDescriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDescriptionKeyPressed
        text = jtxtDescription.getText();
        if (text.length() == 30) {
            jtxtDescription.setEditable(false);
            if (evt.getKeyChar() == evt.VK_BACK_SPACE || evt.getKeyChar() == evt.VK_DELETE || evt.getKeyChar() == evt.VK_LEFT || evt.getKeyChar() == evt.VK_RIGHT) {
                jtxtDescription.setEditable(true);
            }
        } else {
            jtxtDescription.setEditable(true);
        }
    }//GEN-LAST:event_jtxtDescriptionKeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnEdit;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JComboBox jcmbName;
    private javax.swing.JComboBox jcmbType;
    private com.toedter.calendar.JDateChooser jdteDate;
    private javax.swing.JTable jtblWageAdvance;
    private javax.swing.JTextField jtxtAmount;
    private javax.swing.JTextField jtxtDescription;
    // End of variables declaration//GEN-END:variables
}
