/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rose;

import java.awt.Component;
import java.awt.Container;
import java.awt.FocusTraversalPolicy;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Joel
 */
public class JIFraToCuttingMaster2 extends javax.swing.JInternalFrame {

    String text;
    DefaultTableModel model;
    Connection con = null;
    ResultSet rs = null;
    ResultSet rs1 = null;
    ResultSet rs2 = null;
    Statement stmt = null;
    Statement stmt1 = null;
    Statement stmt2 = null;
    String query = null, status;
    String[] orderno, groupno, itemno;
    int rowcount = 0, slno = 0, stsl = 0, count = 0, qty = 0, temp = 0, takenqty = 0;
    String today = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
     

    public JIFraToCuttingMaster2() {
        try {
            initComponents();
            MyTraversalPolicy policy = new MyTraversalPolicy();
            setFocusTraversalPolicy(policy);
            model = (DefaultTableModel) jtblCuttingMaster.getModel();
            jDteDateGiven.setDate(new Date());
            jdteTakeDate.setDate(new Date());
            con = new DBConnection().connect();
            stmt = con.createStatement();
            query = "select group_no,cutting_master from mst_group where flag!='D' and year(date_created)='" + Global.year + "'";
            rs = stmt.executeQuery(query);
            jcmbCuttingMaster.addItem("");
            while (rs.next()) {
                jcmbCuttingMaster.addItem(rs.getString(1) + "   " + rs.getString(2));
            }
            query = "select order_no,student_name from mst_student where school_no='" + Global.getSchoolno() + "' and flag!= 'D'";
            rs = stmt.executeQuery(query);
            jcmbOrderNo.addItem("");
            while (rs.next()) {
                jcmbOrderNo.addItem(rs.getString(1) + "   " + rs.getString(2));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } finally {
            try {
                if (!rs.isClosed()) {
                    rs.close();
                }
                if (!con.isClosed()) {
                    con.close();
                }
                if (!stmt.isClosed()) {
                    stmt.isClosed();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcmbCuttingMaster = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jcmbOrderNo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jDteDateGiven = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblCuttingMaster = new javax.swing.JTable();
        jbtnGive = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jcmbItem = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jtxtQty = new javax.swing.JTextField();
        jbtnTake = new javax.swing.JButton();
        jdteTakeDate = new com.toedter.calendar.JDateChooser();
        jBtnDelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtxtQty1 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Cutting Master");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Cutting Master");

        jLabel2.setText("Order No.");

        jcmbOrderNo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbOrderNoItemStateChanged(evt);
            }
        });

        jLabel3.setText("Date");

        jDteDateGiven.setDateFormatString("dd-MM-yyyy");

        jtblCuttingMaster.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Order No.", "Student Name", "Cutting Master", "Item", "Quantity", "Date Given", "Date Recieved", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblCuttingMaster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblCuttingMasterMouseClicked(evt);
            }
        });
        jtblCuttingMaster.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtblCuttingMasterPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jtblCuttingMaster);
        jtblCuttingMaster.getColumnModel().getColumn(0).setMinWidth(0);
        jtblCuttingMaster.getColumnModel().getColumn(0).setPreferredWidth(0);
        jtblCuttingMaster.getColumnModel().getColumn(0).setMaxWidth(0);
        jtblCuttingMaster.getColumnModel().getColumn(1).setMinWidth(60);
        jtblCuttingMaster.getColumnModel().getColumn(1).setPreferredWidth(60);
        jtblCuttingMaster.getColumnModel().getColumn(1).setMaxWidth(60);
        jtblCuttingMaster.getColumnModel().getColumn(5).setMinWidth(60);
        jtblCuttingMaster.getColumnModel().getColumn(5).setPreferredWidth(60);
        jtblCuttingMaster.getColumnModel().getColumn(5).setMaxWidth(60);
        jtblCuttingMaster.getColumnModel().getColumn(6).setMinWidth(80);
        jtblCuttingMaster.getColumnModel().getColumn(6).setPreferredWidth(80);
        jtblCuttingMaster.getColumnModel().getColumn(6).setMaxWidth(80);
        jtblCuttingMaster.getColumnModel().getColumn(7).setMinWidth(80);
        jtblCuttingMaster.getColumnModel().getColumn(7).setPreferredWidth(80);
        jtblCuttingMaster.getColumnModel().getColumn(7).setMaxWidth(80);
        jtblCuttingMaster.getColumnModel().getColumn(8).setMinWidth(60);
        jtblCuttingMaster.getColumnModel().getColumn(8).setPreferredWidth(60);
        jtblCuttingMaster.getColumnModel().getColumn(8).setMaxWidth(60);

        jbtnGive.setText("GIVE");
        jbtnGive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGiveActionPerformed(evt);
            }
        });

        jLabel5.setText("Item");

        jcmbItem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbItemItemStateChanged(evt);
            }
        });

        jLabel6.setText("Quantity");

        jtxtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtQtyKeyPressed(evt);
            }
        });

        jbtnTake.setText("TAKE");
        jbtnTake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTakeActionPerformed(evt);
            }
        });

        jBtnDelete.setText("DELETE");
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantity");

        jtxtQty1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtQty1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcmbItem, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcmbCuttingMaster, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcmbOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDteDateGiven, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jbtnGive)))
                        .addGap(0, 95, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jdteTakeDate, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtQty1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnTake)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnDelete)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcmbCuttingMaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jcmbOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jDteDateGiven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jcmbItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jtxtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jbtnGive))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnTake)
                        .addComponent(jBtnDelete)
                        .addComponent(jLabel4)
                        .addComponent(jtxtQty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdteTakeDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private class MyTraversalPolicy extends FocusTraversalPolicy {

        @Override
        public Component getComponentAfter(Container aContainer, Component aComponent) {
            if (aComponent.equals(jcmbCuttingMaster)) {
                return jcmbOrderNo;
            } else if (aComponent.equals(jcmbOrderNo)) {
                return jcmbItem;
            } else if (aComponent.equals(jcmbItem)) {
                return jtxtQty;
            } else if (aComponent.equals(jtxtQty)) {
                return jDteDateGiven;
            } else if (aComponent.equals(jDteDateGiven)) {
                return jbtnGive;
            } else if (aComponent.equals(jbtnGive)) {
                return jdteTakeDate;
            } else if (aComponent.equals(jdteTakeDate)) {
                return jtxtQty1;
            } else if (aComponent.equals(jtxtQty1)) {
                return jbtnTake;
            } else if (aComponent.equals(jbtnTake)) {
                return jBtnDelete;
            } else if (aComponent.equals(jBtnDelete)) {
                return jcmbCuttingMaster;
            }
            return jcmbCuttingMaster;

        }

        @Override
        public Component getComponentBefore(Container aContainer, Component aComponent) {
            if (aComponent.equals(jcmbCuttingMaster)) {
                return jBtnDelete;
            } else if (aComponent.equals(jcmbOrderNo)) {
                return jcmbCuttingMaster;
            } else if (aComponent.equals(jcmbItem)) {
                return jcmbOrderNo;
            } else if (aComponent.equals(jtxtQty)) {
                return jcmbItem;
            } else if (aComponent.equals(jDteDateGiven)) {
                return jtxtQty;
            } else if (aComponent.equals(jbtnGive)) {
                return jDteDateGiven;
            } else if (aComponent.equals(jdteTakeDate)) {
                return jbtnGive;
            } else if (aComponent.equals(jtxtQty1)) {
                return jdteTakeDate;
            } else if (aComponent.equals(jbtnTake)) {
                return jtxtQty1;
            } else if (aComponent.equals(jBtnDelete)) {
                return jbtnTake;
            }
            return jcmbCuttingMaster;
        }

        @Override
        public Component getFirstComponent(Container aContainer) {
            return jcmbCuttingMaster;

        }

        @Override
        public Component getLastComponent(Container aContainer) {
            return jbtnTake;

        }

        @Override
        public Component getDefaultComponent(Container aContainer) {
            return jcmbCuttingMaster;

        }
    }
    private void jcmbOrderNoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbOrderNoItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (!jcmbOrderNo.getSelectedItem().equals("")) {
                try {
                    con = new DBConnection().connect();
                    stmt = con.createStatement();
                    orderno = jcmbOrderNo.getSelectedItem().toString().split("   ");
                    query = "select stsl_no from mst_student where order_no = '" + orderno[0] + "' and school_no='" + Global.getSchoolno() + "' and flag!='D'";
                    rs = stmt.executeQuery(query);
                    if (rs.next()) {
                        stsl = rs.getInt(1);
                    }
                    query = "select a.item_no,b.item_name from mst_student_detail a join mst_item b on a.item_no = b.item_no join mst_category c on b.cat_id = c.cat_id  where a.stsl_no = '" + stsl + "' and c.excluded = 0 and a.flag!='D' and b.flag!='D' and c.flag!='D'";
                    rs = stmt.executeQuery(query);
                    jcmbItem.removeAllItems();
                    jcmbItem.addItem("");
                    jcmbItem.addItem("All");
                    while (rs.next()) {
                        jcmbItem.addItem(rs.getString(1) + "   " + rs.getString(2));
                    }
                    populatemastertable(orderno[0]);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                } finally {
                    try {
                        if (!rs.isClosed()) {
                            rs.close();
                        }
                        if (!con.isClosed()) {
                            con.close();
                        }
                        if (!stmt.isClosed()) {
                            stmt.isClosed();
                        }
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage());
                    }
                }
            }
        } else {
            jcmbItem.removeAllItems();
        }
    }//GEN-LAST:event_jcmbOrderNoItemStateChanged
    private void populatemastertable(String orderno) {
        try {
            con = new DBConnection().connect();
            stmt = con.createStatement();
            query = "select a.sl_no,b.order_no,b.student_name,c.cutting_master,d.item_name,a.qty,a.date_given,a.date_recieved,a.status from trn_cm a,mst_student b,mst_group c,mst_item d where a.group_no = c.group_no and a.stsl_no = b.stsl_no and b.school_no = '" + Global.getSchoolno() + "' and d.item_no = a.item_no and a.flag != 'D' and b.flag != 'D' and c.flag != 'D' and d.flag != 'D' and b.order_no='" + orderno + "'";
            rs = stmt.executeQuery(query);
            rowcount = jtblCuttingMaster.getRowCount();
            for (int i = 0; i < rowcount; i++) {
                model.removeRow(0);
            }
            while (rs.next()) {
                model.addRow(new Object[]{});
                jtblCuttingMaster.setValueAt(rs.getString(1), jtblCuttingMaster.getRowCount() - 1, 0);
                jtblCuttingMaster.setValueAt(rs.getString(2), jtblCuttingMaster.getRowCount() - 1, 1);
                jtblCuttingMaster.setValueAt(rs.getString(3), jtblCuttingMaster.getRowCount() - 1, 2);
                jtblCuttingMaster.setValueAt(rs.getString(4), jtblCuttingMaster.getRowCount() - 1, 3);
                jtblCuttingMaster.setValueAt(rs.getString(5), jtblCuttingMaster.getRowCount() - 1, 4);
                jtblCuttingMaster.setValueAt(rs.getString(6), jtblCuttingMaster.getRowCount() - 1, 5);
                jtblCuttingMaster.setValueAt(rs.getString(7), jtblCuttingMaster.getRowCount() - 1, 6);
                jtblCuttingMaster.setValueAt(rs.getString(8), jtblCuttingMaster.getRowCount() - 1, 7);
                jtblCuttingMaster.setValueAt(rs.getString(9), jtblCuttingMaster.getRowCount() - 1, 8);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } finally {
            try {
                if (!rs.isClosed()) {
                    rs.close();
                }
                if (!con.isClosed()) {
                    con.close();
                }
                if (!stmt.isClosed()) {
                    stmt.isClosed();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }
    private void jbtnGiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGiveActionPerformed
        if (jcmbCuttingMaster.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(this, "Please select a cutting master", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else if (jcmbOrderNo.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(this, "Please select an order no.", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else if (jDteDateGiven.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please select a date", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else if (jcmbItem.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(this, "Please select an item", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                orderno = jcmbOrderNo.getSelectedItem().toString().split("   ");
                groupno = jcmbCuttingMaster.getSelectedItem().toString().split("   ");
                con = new DBConnection().connect();
                con.setAutoCommit(false);
                stmt1 = con.createStatement();
                stmt = con.createStatement();
                stmt2 = con.createStatement();
                int i = 0;
                temp = 0;
                if (jcmbItem.getSelectedItem().equals("All")) {
                    query = "select a.item_no,a.qty from mst_student_detail a join mst_item b on a.item_no = b.item_no join mst_category c on b.cat_id = c.cat_id  where a.stsl_no = '" + stsl + "' and c.excluded = 0  and  a.flag!='D' and b.flag!='D' and c.flag!='D'";
                    rs = stmt.executeQuery(query);
                    while (rs.next()) {
                        query = "select item_no,qty from trn_cm where stsl_no = '" + stsl + "' and item_no ='" + rs.getString(1) + "' and flag!='D' group by item_no";
                        rs1 = stmt1.executeQuery(query);
                        if (rs1.next()) {
                            temp = rs.getInt(2) - rs1.getInt(2);
                            if (temp > 0) {
                                query = "select sl_no,qty from trn_cm where stsl_no ='" + stsl + "' and item_no = '" + rs.getString(1) + "' and date_given = '" + today + "' and group_no = '" + groupno[0] + "' and status='P' and flag!='D'";
                                rs2 = stmt2.executeQuery(query);
                                if (rs2.next()) {
                                    temp = temp + rs2.getInt(2);
                                    query = "update trn_cm set qty = '" + temp + "' where sl_no='" + rs2.getString(1) + "'";
                                    i = i + stmt2.executeUpdate(query);
                                } else {
                                    query = "insert into trn_cm(group_no,stsl_no,item_no,qty,status,date_given,flag,date_created) values('" + groupno[0] + "','" + stsl + "','" + rs.getString(1) + "','" + temp + "','P','" + new SimpleDateFormat("yyyy-MM-dd").format(jDteDateGiven.getDate()) + "','I','" + today + "')";
                                    i = i + stmt2.executeUpdate(query);
                                }
                            }
                        } else {
                            query = "insert into trn_cm(group_no,stsl_no,item_no,qty,status,date_given,flag,date_created) values('" + groupno[0] + "','" + stsl + "','" + rs.getString(1) + "','" + rs.getString(2) + "','P','" + new SimpleDateFormat("yyyy-MM-dd").format(jDteDateGiven.getDate()) + "','I','" + today + "')";
                            i = i + stmt1.executeUpdate(query);
                        }
                    }
                } else {
                    if (jtxtQty.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Please enter a valid quantity", "Info", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        itemno = jcmbItem.getSelectedItem().toString().split("   ");
                        query = "select item_no,qty from mst_student_detail where stsl_no = '" + stsl + "' and item_no = '" + itemno[0] + "' and flag!='D'";
                        rs = stmt.executeQuery(query);
                        if (rs.next()) {
                            if (rs.getInt(2) >= Integer.parseInt(jtxtQty.getText())) {
                                query = "select item_no,qty from trn_cm where stsl_no = '" + stsl + "' and item_no ='" + itemno[0] + "' and flag!='D' group by item_no";
                                rs1 = stmt1.executeQuery(query);
                                if (rs1.next()) {
                                    temp = rs.getInt(2) - rs1.getInt(2);
                                    if (temp > 0) {
                                        if (temp >= Integer.parseInt(jtxtQty.getText())) {
                                            query = "select sl_no,qty from trn_cm where stsl_no ='" + stsl + "' and item_no = '" + rs.getString(1) + "' and date_given = '" + today + "' and group_no = '" + groupno[0] + "' and status='P' and flag!='D'";
                                            rs2 = stmt2.executeQuery(query);
                                            if (rs2.next()) {
                                                temp = Integer.parseInt(jtxtQty.getText()) + rs2.getInt(2);
                                                query = "update trn_cm set qty = '" + temp + "' where sl_no='" + rs2.getString(1) + "'";
                                                i = i + stmt2.executeUpdate(query);
                                            } else {
                                                query = "insert into trn_cm(group_no,stsl_no,item_no,qty,status,date_given,flag,date_created) values('" + groupno[0] + "','" + stsl + "','" + itemno[0] + "','" + jtxtQty.getText() + "','P','" + new SimpleDateFormat("yyyy-MM-dd").format(jDteDateGiven.getDate()) + "','I','" + today + "')";
                                                i = i + stmt2.executeUpdate(query);
                                            }
                                        } else {
                                            JOptionPane.showMessageDialog(this, "The quantity entered has exceeded please check the order!", "Info", JOptionPane.INFORMATION_MESSAGE);
                                        }
                                    }
                                } else {
                                    query = "insert into trn_cm(group_no,stsl_no,item_no,qty,status,date_given,flag,date_created) values('" + groupno[0] + "','" + stsl + "','" + itemno[0] + "','" + jtxtQty.getText() + "','P','" + new SimpleDateFormat("yyyy-MM-dd").format(jDteDateGiven.getDate()) + "','I','" + today + "')";
                                    i = i + stmt1.executeUpdate(query);
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "The Student has not order this much quantity!", "Info", JOptionPane.INFORMATION_MESSAGE);
                            }
                        }
                    }
                }
                if (i > 0) {
                    con.commit();
                    JOptionPane.showMessageDialog(this, "Inserted Successfull!", "Info", JOptionPane.INFORMATION_MESSAGE);
                    populatemastertable(orderno[0]);
                    jcmbItem.setSelectedItem("");
                    jtxtQty.setText("");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());

            } finally {
                jcmbOrderNo.grabFocus();
                try {
                    if (!rs.isClosed()) {
                        rs.close();
                    }
                    if (!con.isClosed()) {
                        con.close();
                    }
                    if (!stmt.isClosed()) {
                        stmt.isClosed();
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            }

        }
    }//GEN-LAST:event_jbtnGiveActionPerformed

    private void jcmbItemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbItemItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (jcmbItem.getSelectedItem().equals("All")) {
                jtxtQty.setEnabled(false);
                jtxtQty.setText("");
            } else {
                if (!jcmbItem.getSelectedItem().equals("")) {
                    try {
                        itemno = jcmbItem.getSelectedItem().toString().split("   ");
                        jtxtQty.setEnabled(true);
                        con = new DBConnection().connect();
                        stmt = con.createStatement();
                        query = "select qty from mst_student_detail where item_no = '" + itemno[0] + "' and stsl_no = '" + stsl + "' and flag!='D' ";
                        rs = stmt.executeQuery(query);
                        if (rs.next()) {
                            jtxtQty.setText(rs.getString(1));
                        }
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage());
                    } finally {
                        try {
                            if (!rs.isClosed()) {
                                rs.close();
                            }
                            if (!con.isClosed()) {
                                con.close();
                            }
                            if (!stmt.isClosed()) {
                                stmt.isClosed();
                            }
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(this, ex.getMessage());
                        }
                    }
                } else {
                    jtxtQty.setText("");
                }
            }
        }
    }//GEN-LAST:event_jcmbItemItemStateChanged

    private void jtxtQtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtQtyKeyPressed
        text = "";
        text = jtxtQty.getText();
        if (text.length() == 2) {
            jtxtQty.setEditable(false);
            if (evt.getKeyChar() == evt.VK_BACK_SPACE || evt.getKeyChar() == evt.VK_DELETE || evt.getKeyChar() == evt.VK_LEFT || evt.getKeyChar() == evt.VK_RIGHT) {
                jtxtQty.setEditable(true);
            }
        } else if (evt.getKeyChar() >= evt.VK_0 && evt.getKeyChar() <= evt.VK_9 || evt.getKeyChar() == evt.VK_BACK_SPACE || evt.getKeyChar() == evt.VK_DELETE || evt.getKeyChar() == evt.VK_LEFT || evt.getKeyChar() == evt.VK_RIGHT || evt.getKeyChar() == evt.VK_PERIOD) {
            jtxtQty.setEditable(true);
        } else {
            jtxtQty.setEditable(false);
        }
    }//GEN-LAST:event_jtxtQtyKeyPressed

    private void jbtnTakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTakeActionPerformed
        try {
            if (jtblCuttingMaster.getRowCount() > 0) {
                if (jtblCuttingMaster.getSelectedRow() < 0) {
                    int b = JOptionPane.showConfirmDialog(this, "Do you want a take 'ALL' items from the cutting master?", "Confirm", JOptionPane.YES_NO_OPTION);
                    if (b == JOptionPane.YES_OPTION) {
                        temp = 0;
                        for (int i = 0; i < jtblCuttingMaster.getRowCount(); i++) {
                            if (jtblCuttingMaster.getValueAt(i, 8).toString().equals("C")) {
                                temp++;
                            }
                        }
                        if (temp != jtblCuttingMaster.getRowCount()) {
                            temp = 0;
                            orderno = jcmbOrderNo.getSelectedItem().toString().split("   ");
                            con = new DBConnection().connect();
                            con.setAutoCommit(false);
                            stmt = con.createStatement();
                            for (int i = 0; i < jtblCuttingMaster.getRowCount(); i++) {
                                if (jtblCuttingMaster.getValueAt(i, 8).toString().equals("P")) {
                                    query = "update trn_cm set date_recieved='" + new SimpleDateFormat("yyyy-MM-dd").format(jdteTakeDate.getDate()) + "', date_updated='" + today + "',flag='I',status ='C' where sl_no = '" + jtblCuttingMaster.getValueAt(i, 0) + "' ";
                                    temp = temp + stmt.executeUpdate(query);
                                }
                            }
                            if (temp > 0) {
                                JOptionPane.showMessageDialog(this, "Update Successfull!", "Info", JOptionPane.INFORMATION_MESSAGE);
                                con.commit();
                                populatemastertable(orderno[0]);
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "All item have already been taken", "Info", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                } else if (jdteTakeDate.getDate() == null) {
                    JOptionPane.showMessageDialog(this, "Please select a date", "Info", JOptionPane.INFORMATION_MESSAGE);
                } else if (jtblCuttingMaster.getValueAt(jtblCuttingMaster.getSelectedRow(), 8).toString().equals("C")) {
                    JOptionPane.showMessageDialog(this, "This item has already been taken", "Info", JOptionPane.INFORMATION_MESSAGE);
                } else if (jtxtQty1.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Please enter a quantity", "Info", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    int b = JOptionPane.showConfirmDialog(this, "Do you want a take this item from the cutting master?", "Confirm", JOptionPane.YES_NO_OPTION);
                    if (b == JOptionPane.YES_OPTION) {
                        if (Integer.parseInt(jtxtQty1.getText()) > 0) {
                            int i = 0;
                            con = new DBConnection().connect();
                            con.setAutoCommit(false);
                            stmt = con.createStatement();
                            stmt2 = con.createStatement();
                            orderno = jcmbOrderNo.getSelectedItem().toString().split("   ");
                            if (Integer.parseInt(jtxtQty1.getText()) == takenqty) {
                                query = "update trn_cm set date_recieved='" + new SimpleDateFormat("yyyy-MM-dd").format(jdteTakeDate.getDate()) + "', date_updated='" + today + "',flag='I',status ='C' where sl_no = '" + slno + "' ";
                                i = stmt.executeUpdate(query);
                            } else if (Integer.parseInt(jtxtQty1.getText()) < takenqty) {
                                temp = takenqty - Integer.parseInt(jtxtQty1.getText());
                                query = "update trn_cm set date_updated='" + today + "',flag='I',qty = '" + temp + "'  where sl_no = '" + slno + "' ";
                                i = stmt.executeUpdate(query);
                                query = "select group_no,stsl_no,item_no,qty,status,date_given,flag,date_created from trn_cm where sl_no = '" + slno + "'";
                                rs = stmt.executeQuery(query);
                                if (rs.next()) {
                                    query = "insert into trn_cm(group_no,stsl_no,item_no,qty,status,date_given,date_recieved,flag,date_created) values('" + rs.getString(1) + "','" + rs.getString(2) + "','" + rs.getString(3) + "','" + jtxtQty1.getText() + "','C','" + new SimpleDateFormat("yyyy-MM-dd").format(jdteTakeDate.getDate()) + "','" + today + "','I','" + rs.getString(8) + "')";
                                    i = i + stmt2.executeUpdate(query);
                                }
                            }
                            if (i > 0) {
                                con.commit();
                                JOptionPane.showMessageDialog(this, "Update Successfull!", "Info", JOptionPane.INFORMATION_MESSAGE);
                                populatemastertable(orderno[0]);
                            }
                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please select an order number to continue!", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } finally {
            jcmbOrderNo.grabFocus();
            try {
                if (!rs.isClosed()) {
                    rs.close();
                }
                if (!con.isClosed()) {
                    con.close();
                }
                if (!stmt.isClosed()) {
                    stmt.isClosed();
                }
                if (!stmt2.isClosed()) {
                    stmt2.isClosed();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_jbtnTakeActionPerformed

    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
        if (jtblCuttingMaster.getRowCount() > 0) {
            if (jtblCuttingMaster.getSelectedRow() > -1) {
                int b = JOptionPane.showConfirmDialog(this, "Do you want delete the record?", "Confirm", JOptionPane.YES_NO_OPTION);
                if (b == JOptionPane.YES_OPTION) {
                    try {
                        temp = 0;
                        orderno = jcmbOrderNo.getSelectedItem().toString().split("   ");
                        con = new DBConnection().connect();
                        con.setAutoCommit(false);
                        stmt = con.createStatement();
                        query = "update trn_cm set date_updated='" + today + "',flag='D' where sl_no = '" + jtblCuttingMaster.getValueAt(jtblCuttingMaster.getSelectedRow(), 0) + "' ";
                        temp = stmt.executeUpdate(query);
                        if (temp > 0) {
                            JOptionPane.showMessageDialog(this, "Delete Successfull!", "Info", JOptionPane.INFORMATION_MESSAGE);
                            con.commit();
                            populatemastertable(orderno[0]);
                        }
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage());
                    } finally {
                        try {
                            if (!rs.isClosed()) {
                                rs.close();
                            }
                            if (!con.isClosed()) {
                                con.close();
                            }
                            if (!stmt.isClosed()) {
                                stmt.isClosed();
                            }
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(this, ex.getMessage());
                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please select a record to delete", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBtnDeleteActionPerformed

    private void jtblCuttingMasterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblCuttingMasterMouseClicked
        if (jtblCuttingMaster.getSelectedRow() > -1) {
            jtxtQty1.setText(jtblCuttingMaster.getValueAt(jtblCuttingMaster.getSelectedRow(), 5).toString());
            takenqty = Integer.parseInt(jtblCuttingMaster.getValueAt(jtblCuttingMaster.getSelectedRow(), 5).toString());
            slno = Integer.parseInt(jtblCuttingMaster.getValueAt(jtblCuttingMaster.getSelectedRow(), 0).toString());
            status = jtblCuttingMaster.getValueAt(jtblCuttingMaster.getSelectedRow(), 8).toString();
        }
    }//GEN-LAST:event_jtblCuttingMasterMouseClicked

    private void jtblCuttingMasterPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtblCuttingMasterPropertyChange
    }//GEN-LAST:event_jtblCuttingMasterPropertyChange

    private void jtxtQty1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtQty1KeyPressed
        text = "";
        text = jtxtQty.getText();
        if (text.length() == 2) {
            jtxtQty.setEditable(false);
            if (evt.getKeyChar() == evt.VK_BACK_SPACE || evt.getKeyChar() == evt.VK_DELETE || evt.getKeyChar() == evt.VK_LEFT || evt.getKeyChar() == evt.VK_RIGHT) {
                jtxtQty.setEditable(true);
            }
        } else if (evt.getKeyChar() >= evt.VK_0 && evt.getKeyChar() <= evt.VK_9 || evt.getKeyChar() == evt.VK_BACK_SPACE || evt.getKeyChar() == evt.VK_DELETE || evt.getKeyChar() == evt.VK_LEFT || evt.getKeyChar() == evt.VK_RIGHT || evt.getKeyChar() == evt.VK_PERIOD) {
            jtxtQty.setEditable(true);
        } else {
            jtxtQty.setEditable(false);
        }
    }//GEN-LAST:event_jtxtQty1KeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDelete;
    private com.toedter.calendar.JDateChooser jDteDateGiven;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnGive;
    private javax.swing.JButton jbtnTake;
    private javax.swing.JComboBox jcmbCuttingMaster;
    private javax.swing.JComboBox jcmbItem;
    private javax.swing.JComboBox jcmbOrderNo;
    private com.toedter.calendar.JDateChooser jdteTakeDate;
    private javax.swing.JTable jtblCuttingMaster;
    private javax.swing.JTextField jtxtQty;
    private javax.swing.JTextField jtxtQty1;
    // End of variables declaration//GEN-END:variables
}
