/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rose;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Joel
 */
public class JIFraDeleteClass extends javax.swing.JInternalFrame {

    DefaultTableModel model1;
    Connection con = null;
    ResultSet rs = null;
    Statement stmt = null;
    String query = "";
    int r;

    public JIFraDeleteClass() {
        initComponents();
        populatelist();
    }

    private void populatelist() {
        try {
            if (jCmbClass.getItemCount() > 0) {
                jCmbClass.removeAllItems();
            }
            con = new DBConnection().connect();
            stmt = con.createStatement();
            query = "select class from mst_class where flag != 'D' order by class*1";
            rs = stmt.executeQuery(query);
            jCmbClass.addItem("");
            while (rs.next()) {
                jCmbClass.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } finally {
            try {
                if (!rs.isClosed()) {
                    rs.close();
                }
                if (!con.isClosed()) {
                    con.close();
                }
                if (!stmt.isClosed()) {
                    stmt.isClosed();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCmbClass = new javax.swing.JComboBox();
        jBtnClass = new javax.swing.JButton();

        setClosable(true);
        setTitle("Delete Class");

        jLabel1.setText("Class");

        jBtnClass.setText("Delete");
        jBtnClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCmbClass, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jBtnClass)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCmbClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnClass))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClassActionPerformed
        try {
            if ((jCmbClass.getItemCount() > 1) && (!jCmbClass.getSelectedItem().equals(""))) {
                int b = JOptionPane.showConfirmDialog(this, "Do you want delete the class?", "Confirm", JOptionPane.YES_NO_OPTION);
                if (b == JOptionPane.YES_OPTION) {
                    con = new DBConnection().connect();
                    stmt = con.createStatement();
                    query = "select class_no from mst_class where class = '" + jCmbClass.getSelectedItem().toString() + "' and flag!='D'";
                    rs = stmt.executeQuery(query);
                    String classno = null;
                    if (rs.next()) {
                        classno = rs.getString(1);
                    }
                    query = "update mst_class set flag = 'D' where class_no = '" + classno + "'";
                    r = r + stmt.executeUpdate(query);                    
                    if (r > 0) {
                        JOptionPane.showMessageDialog(this, "Deleted Successfully!", "Info", JOptionPane.INFORMATION_MESSAGE);
                        populatelist();
                    }
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } finally {
            try {
                if (!rs.isClosed()) {
                    rs.close();
                }
                if (!con.isClosed()) {
                    con.close();
                }
                if (!stmt.isClosed()) {
                    stmt.isClosed();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_jBtnClassActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnClass;
    private javax.swing.JComboBox jCmbClass;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
