/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rose;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Betsy
 */
public class JIFraViewPendingCM extends javax.swing.JInternalFrame {

    DefaultTableModel modell;
    DefaultTableModel model2;
    Connection con = null;
    ResultSet rs = null;
    Statement stmt = null;
    String query = null;
    String[] groupno;
    int rowcount = 0;
    int[] selected;
    String today = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
     

    public JIFraViewPendingCM() {
        try {
            initComponents();
            modell = (DefaultTableModel) jtblCuttingMaster.getModel();
            model2 = (DefaultTableModel) jtblItem.getModel();
            jtblCuttingMaster.setAutoCreateRowSorter(true);
            con = new DBConnection().connect();
            stmt = con.createStatement();
            query = "select group_no,cutting_master from mst_group where flag!='D' and year(date_created)='"+Global.year+"'";
            rs = stmt.executeQuery(query);
            jcmbCuttingMaster.addItem("");
            while (rs.next()) {
                jcmbCuttingMaster.addItem(rs.getString(1) + "   " + rs.getString(2));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } finally {
            try {
                if (!rs.isClosed()) {
                    rs.close();
                }
                if (!con.isClosed()) {
                    con.close();
                }
                if (!stmt.isClosed()) {
                    stmt.isClosed();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcmbCuttingMaster = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblCuttingMaster = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jcmbStatus = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jdteDate = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblItem = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jdteTakeDate = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pending List - Cutting Master");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Cutting Master");

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtblCuttingMaster.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Order No.", "Student Name", "Cutting Master", "Item", "Quantity", "Date Given", "Date Recieved", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblCuttingMaster);
        jtblCuttingMaster.getColumnModel().getColumn(0).setMinWidth(0);
        jtblCuttingMaster.getColumnModel().getColumn(0).setPreferredWidth(0);
        jtblCuttingMaster.getColumnModel().getColumn(0).setMaxWidth(0);
        jtblCuttingMaster.getColumnModel().getColumn(1).setMinWidth(70);
        jtblCuttingMaster.getColumnModel().getColumn(1).setPreferredWidth(70);
        jtblCuttingMaster.getColumnModel().getColumn(1).setMaxWidth(70);
        jtblCuttingMaster.getColumnModel().getColumn(5).setMinWidth(55);
        jtblCuttingMaster.getColumnModel().getColumn(5).setPreferredWidth(55);
        jtblCuttingMaster.getColumnModel().getColumn(5).setMaxWidth(55);
        jtblCuttingMaster.getColumnModel().getColumn(6).setMinWidth(100);
        jtblCuttingMaster.getColumnModel().getColumn(6).setPreferredWidth(100);
        jtblCuttingMaster.getColumnModel().getColumn(6).setMaxWidth(100);
        jtblCuttingMaster.getColumnModel().getColumn(7).setMinWidth(100);
        jtblCuttingMaster.getColumnModel().getColumn(7).setPreferredWidth(100);
        jtblCuttingMaster.getColumnModel().getColumn(7).setMaxWidth(100);
        jtblCuttingMaster.getColumnModel().getColumn(8).setMinWidth(50);
        jtblCuttingMaster.getColumnModel().getColumn(8).setPreferredWidth(50);
        jtblCuttingMaster.getColumnModel().getColumn(8).setMaxWidth(50);

        jLabel2.setText("Status");

        jcmbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pending", "Completed" }));

        jLabel3.setText("Date");

        jtblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Total No."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtblItem);
        jtblItem.getColumnModel().getColumn(1).setPreferredWidth(100);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setText("Date");

        jButton2.setText("Take");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdteTakeDate, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jdteTakeDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcmbCuttingMaster, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdteDate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jcmbCuttingMaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addComponent(jLabel2)
                        .addComponent(jcmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jdteDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jcmbCuttingMaster.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(this, "Please select a cutting master", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            populatemastertable();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jdteTakeDate.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please select a date", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtblCuttingMaster.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Select an item to take", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                int i = 0;
                con = new DBConnection().connect();
                con.setAutoCommit(false);
                stmt = con.createStatement();
                selected = jtblCuttingMaster.getSelectedRows();
                for (int j = 0; j < selected.length; j++) {
                    if (!jtblCuttingMaster.getValueAt(selected[j], 8).equals("C")) {
                        query = "update trn_cm set date_recieved='" + new SimpleDateFormat("yyyy-MM-dd").format(jdteTakeDate.getDate()) + "', date_updated='" + today + "',flag='I',status ='C' where sl_no = '" + jtblCuttingMaster.getValueAt(selected[j], 0) + "' ";
                        i = stmt.executeUpdate(query);
                    }
                }
                if (i > 0) {
                    JOptionPane.showMessageDialog(this, "Update Successfull!", "Info", JOptionPane.INFORMATION_MESSAGE);
                    con.commit();
                    jButton1ActionPerformed(evt);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            } finally {
                try {                   
                    if (!con.isClosed()) {
                        con.close();
                    }
                    if (!stmt.isClosed()) {
                        stmt.isClosed();
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed
    private void populatemastertable() {
        try {
            con = new DBConnection().connect();
            stmt = con.createStatement();
            groupno = jcmbCuttingMaster.getSelectedItem().toString().split("   ");
            rowcount = jtblItem.getRowCount();
            for (int i = 0; i < rowcount; i++) {
                model2.removeRow(0);
            }
            rowcount = modell.getRowCount();
            for (int i = 0; i < rowcount; i++) {
                modell.removeRow(0);
            }
            if (jcmbStatus.getSelectedItem().equals("Pending")) {
                if (jdteDate.getDate() == null) {
                    query = "select a.sl_no,b.order_no,b.student_name,c.cutting_master,d.item_name,a.qty,a.date_given,a.date_recieved,a.status from trn_cm a,mst_student b,mst_group c,mst_item d where a.group_no = c.group_no and a.stsl_no = b.stsl_no and d.item_no = a.item_no and a.status = 'P' and a.flag != 'D' and b.flag != 'D' and c.flag != 'D' and d.flag != 'D' and a.group_no = '" + groupno[0] + "' ";
                } else {
                    query = "select a.sl_no,b.order_no,b.student_name,c.cutting_master,d.item_name,a.qty,a.date_given,a.date_recieved,a.status from trn_cm a,mst_student b,mst_group c,mst_item d where a.group_no = c.group_no and a.stsl_no = b.stsl_no and a.date_given = '" + new SimpleDateFormat("yyyy-MM-dd").format(jdteDate.getDate()) + "' and d.item_no = a.item_no and a.status = 'P' and a.flag != 'D' and b.flag != 'D' and c.flag != 'D' and d.flag != 'D' and a.group_no = '" + groupno[0] + "' ";
                    populateitem("select d.item_name,sum(a.qty) from trn_cm a,mst_student b,mst_group c,mst_item d where a.group_no = c.group_no and a.stsl_no = b.stsl_no and a.date_given = '" + new SimpleDateFormat("yyyy-MM-dd").format(jdteDate.getDate()) + "' and d.item_no = a.item_no and a.status = 'P' and a.flag != 'D' and b.flag != 'D' and c.flag != 'D' and d.flag != 'D' and a.group_no = '" + groupno[0] + "' group by a.item_no");
                }
            } else if (jcmbStatus.getSelectedItem().equals("Completed")) {
                if (jdteDate.getDate() == null) {
                    query = "select a.sl_no,b.order_no,b.student_name,c.cutting_master,d.item_name,a.qty,a.date_given,a.date_recieved,a.status from trn_cm a,mst_student b,mst_group c,mst_item d where a.group_no = c.group_no and a.stsl_no = b.stsl_no and d.item_no = a.item_no and a.status = 'C' and a.flag != 'D' and b.flag != 'D' and c.flag != 'D' and d.flag != 'D' and a.group_no = '" + groupno[0] + "' ";
                } else {
                    query = "select a.sl_no,b.order_no,b.student_name,c.cutting_master,d.item_name,a.qty,a.date_given,a.date_recieved,a.status from trn_cm a,mst_student b,mst_group c,mst_item d where a.group_no = c.group_no and a.stsl_no = b.stsl_no  and a.date_recieved = '" + new SimpleDateFormat("yyyy-MM-dd").format(jdteDate.getDate()) + "'  and d.item_no = a.item_no and a.status = 'C' and a.flag != 'D' and b.flag != 'D' and c.flag != 'D' and d.flag != 'D' and a.group_no = '" + groupno[0] + "' ";
                    populateitem("select d.item_name,sum(a.qty) from trn_cm a,mst_student b,mst_group c,mst_item d where a.group_no = c.group_no and a.stsl_no = b.stsl_no and a.date_recieved = '" + new SimpleDateFormat("yyyy-MM-dd").format(jdteDate.getDate()) + "'  and d.item_no = a.item_no and a.status = 'C' and a.flag != 'D' and b.flag != 'D' and c.flag != 'D' and d.flag != 'D' and a.group_no = '" + groupno[0] + "' group by a.item_no");
                }
            }
            rs = stmt.executeQuery(query);
            while (rs.next()) {
                modell.addRow(new Object[]{});
                jtblCuttingMaster.setValueAt(rs.getString(1), modell.getRowCount() - 1, 0);
                jtblCuttingMaster.setValueAt(rs.getString(2), modell.getRowCount() - 1, 1);
                jtblCuttingMaster.setValueAt(rs.getString(3), modell.getRowCount() - 1, 2);
                jtblCuttingMaster.setValueAt(rs.getString(4), modell.getRowCount() - 1, 3);
                jtblCuttingMaster.setValueAt(rs.getString(5), modell.getRowCount() - 1, 4);
                jtblCuttingMaster.setValueAt(rs.getString(6), modell.getRowCount() - 1, 5);
                jtblCuttingMaster.setValueAt(rs.getString(7), modell.getRowCount() - 1, 6);
                jtblCuttingMaster.setValueAt(rs.getString(8), modell.getRowCount() - 1, 7);
                jtblCuttingMaster.setValueAt(rs.getString(9), modell.getRowCount() - 1, 8);
            }
            if (jcmbStatus.getSelectedItem().equals("Pending") && jtblCuttingMaster.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "There are no pending items with cutting master");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } finally {
            try {
                if (!rs.isClosed()) {
                    rs.close();
                }
                if (!con.isClosed()) {
                    con.close();
                }
                if (!stmt.isClosed()) {
                    stmt.isClosed();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }

    private void populateitem(String q) {
        try {
            rowcount = model2.getRowCount();
            for (int i = 0; i < rowcount; i++) {
                model2.removeRow(0);
            }
            rs = stmt.executeQuery(q);
            while (rs.next()) {
                model2.addRow(new Object[]{});
                jtblItem.setValueAt(rs.getString(1), model2.getRowCount() - 1, 0);
                jtblItem.setValueAt(rs.getString(2), model2.getRowCount() - 1, 1);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jcmbCuttingMaster;
    private javax.swing.JComboBox jcmbStatus;
    private com.toedter.calendar.JDateChooser jdteDate;
    private com.toedter.calendar.JDateChooser jdteTakeDate;
    private javax.swing.JTable jtblCuttingMaster;
    private javax.swing.JTable jtblItem;
    // End of variables declaration//GEN-END:variables
}
