/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rose;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Joel
 */
public class JIFraAddMaterialConsumptionForAll extends javax.swing.JInternalFrame {

    Connection con = null;
    Statement stmt = null;
    Statement stmt1 = null;
    Statement stmt2 = null;
    Statement stmt3 = null;
    String query = null;
    ResultSet rs = null;
    ResultSet rs1 = null;
    ResultSet rs2 = null;
    ResultSet rs3 = null;
    String[] school_no;
    String today = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
     

    public JIFraAddMaterialConsumptionForAll() {
        try {
            initComponents();
            con = new DBConnection().connect();
            stmt = con.createStatement();
            query = "select school_no,school_name from mst_school where flag!='D' and year(date_created)='"+Global.year+"'";
            rs = stmt.executeQuery(query);
            jcmbSchool.removeAllItems();
            jcmbSchool.addItem("");
            while (rs.next()) {
                jcmbSchool.addItem(rs.getString(1) + "   " + rs.getString(2));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcmbSchool = new javax.swing.JComboBox();
        jbtnUpdate = new javax.swing.JButton();

        setClosable(true);
        setTitle("Add Material Consumption For All");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("School");

        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcmbSchool, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jbtnUpdate)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcmbSchool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnUpdate))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        if (jcmbSchool.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(this, "Please select a school", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            school_no = jcmbSchool.getSelectedItem().toString().split("   ");
            int i = 0;
            try {
                con = new DBConnection().connect();
                con.setAutoCommit(false);
                stmt = con.createStatement();
                stmt1 = con.createStatement();
                stmt2 = con.createStatement();
                stmt3 = con.createStatement();
                query = "select stsl_no,class_no from mst_student where school_no='" + school_no[0] + "' and flag!='D'";
                rs = stmt.executeQuery(query);
                while (rs.next()) {
                    query = "select item_no from mst_student_detail where stsl_no = '" + rs.getString(1) + "' and flag!='D'";
                    rs1 = stmt1.executeQuery(query);
                    while (rs1.next()) {
                        query = "select school_no,class_no,item_no,material_no,fixed_mat_length,actual_mat_length from mst_material_consumption where item_no = '" + rs1.getString(1) + "' and school_no = '" + school_no[0] + "' and class_no = '" + rs.getString(2) + "'";
                        rs2 = stmt2.executeQuery(query);
                        while (rs2.next()) {
                            query = "select sl_no from mst_student_mat_detail where stsl_no = '" + rs.getString(1) + "' and item_no = '" + rs2.getString(3) + "' and material_no = '" + rs2.getString(4) + "'";
                            rs3 = stmt3.executeQuery(query);
                            if (!rs3.next()) {
                                query = "INSERT INTO MST_STUDENT_MAT_DETAIL(STSL_NO,ITEM_NO,MATERIAL_NO,FIXED_MAT_LENGTH,ACTUAL_MAT_LENGTH,FLAG,DATE_CREATED) VALUES ('" + rs.getString(1) + "', '" + rs2.getString(3) + "', '" + rs2.getString(4) + "', '" + rs2.getString(5) + "', '" + rs2.getString(6) + "', 'I', '" + today + "')";
                                i = i + stmt3.executeUpdate(query);
                            } else {
                                query = "update mst_student_mat_detail set fixed_mat_length = '" + rs2.getString(5) + "',actual_mat_length = '" + rs2.getString(6) + "' where sl_no = '" + rs3.getString(1) + "'";
                                i = i + stmt3.executeUpdate(query);
                            }
                        }
                    }
                }
                if (i > 0) {
                    con.commit();
                    JOptionPane.showMessageDialog(this, "Successfully updated!", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jbtnUpdateActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JComboBox jcmbSchool;
    // End of variables declaration//GEN-END:variables
}
